// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define("dojo/_base/declare dojo/_base/array dijit/_WidgetBase dijit/_TemplatedMixin dijit/_WidgetsInTemplateMixin dojo/on dojo/Evented dojo/_base/html dojo/_base/lang jimu/symbolUtils jimu/dijit/DrawBox esri/graphic esri/layers/FeatureLayer esri/tasks/query esri/symbols/jsonUtils esri/layers/GraphicsLayer esri/geometry/Circle esri/renderers/SimpleRenderer esri/geometry/geometryEngine".split(" "),function(n,g,p,q,r,d,t,l,h,u,v,m,w,x,c,y,z,A,k){return n([p,q,r,t],{baseClass:"jimu-select-features-tool",
templateString:'\x3cdiv\x3e\x3cdiv data-dojo-attach-point\x3d"drawBoxDiv"\x3e\x3c/div\x3e\x3c/div\x3e',map:null,bufferLayer:null,drawBoxOption:null,nls:null,currentLayerInfo:null,postCreate:function(){this.inherited(arguments);this.map=this.drawBoxOption.map;this.bufferLayer=new y;var a=this._getPolygonSymbol(),b=new A(a);this.bufferLayer.setRenderer(b);this.map.addLayer(this.bufferLayer);this.drawBoxOption.showClear=this.drawBoxOption.showClear;this.drawBoxOption.keepOneGraphic=!0;this.drawBox=new v(this.drawBoxOption);
this.drawBox.setPolygonSymbol(a);a=u.getGreyPinMarkerSymbol();this.drawBox.setPointSymbol(a);this.drawBox.setLineSymbol(c.fromJson({color:[54,93,141,255],width:1.5,type:"esriSLS",style:"esriSLSSolid"}));this.drawBox.placeAt(this.drawBoxDiv);this.own(d(this.drawBox,"user-clear",h.hitch(this,this._onDrawBoxClear)));this.own(d(this.drawBox,"draw-end",h.hitch(this,this._onDrawEnd)));this.drawBox.btnClear?l.removeClass(this.drawBox.btnClear,"jimu-float-trailing"):l.addClass(this.drawBox.btnClear,"jimu-float-leading")},
reset:function(){this.drawBox.reset();this.clearAllGraphics()},clearAllGraphics:function(){this.drawBox.clear();this._clearBufferLayer()},hideTempLayers:function(){this.bufferLayer&&this.bufferLayer.hide();this.drawBox&&this.drawBox.hideLayer()},showTempLayers:function(){this.bufferLayer&&this.bufferLayer.show();this.drawBox&&this.drawBox.showLayer()},deactivate:function(){this.drawBox&&this.drawBox.deactivate()},execute:function(){var a,b,c=!1;if(this.currentLayerInfo){null!==this.currentLayerInfo.url?
a=new w(this.currentLayerInfo.url,{outFields:["*"]}):(a=this.currentLayerInfo,c=!0);var e=this._getGeometryFromDrawBox();"POINT"===e.geoType&&(e=(new z({center:e,geodesic:!0,radius:25,radiusUnit:"esriFeet"})).getExtent());var d=new x;c?(g.forEach(a.graphics,function(a){if(k.intersects(a.geometry,e)){var f=null;switch(a.geometry.type){case "point":f=this._getPointSymbol();break;case "polyline":f=this._getPolylineSymbol();break;case "polygon":f=this._getPolygonSymbol();break;default:f=null}this.bufferLayer.add(new m(a.geometry,
f))}},this),this.drawBox.clear(),b=k.union(g.map(this.bufferLayer.graphics,function(a){return a.geometry})),this.emit("selection-complete",{geometry:b})):(d.geometry=e,a.queryFeatures(d,h.hitch(this,function(a){g.forEach(a.features,function(a){var b=null;switch(a.geometry.type){case "point":b=this._getPointSymbol();break;case "polyline":b=this._getPolylineSymbol();break;case "polygon":b=this._getPolygonSymbol();break;default:b=null}this.bufferLayer.add(new m(a.geometry,b))},this);this.drawBox.clear();
b=k.union(g.map(a.features,function(a){return a.geometry}));this.emit("selection-complete",{geometry:b})})))}},setLayerInfo:function(a){this.currentLayerInfo=a},_getPointSymbol:function(){return c.fromJson({color:[36,181,204,175],size:16,xoffset:0,yoffset:0,type:"esriSMS",style:"esriSMSCircle",outline:{style:"esriSLSSolid",color:[36,181,204,255],width:2,type:"esriSLS"}})},_getPolylineSymbol:function(){return c.fromJson({style:"esriSFSSolid",width:5,color:[36,181,204,175],type:"esriSLS"})},_getPolygonSymbol:function(){return c.fromJson({style:"esriSFSSolid",
color:[36,181,204,175],type:"esriSFS",outline:{style:"esriSLSSolid",color:[36,181,204,255],width:2,type:"esriSLS"}})},_getGeometryFromDrawBox:function(){var a=null,b=this.drawBox.getFirstGraphic();b&&(a=b.geometry);return a},_getGeometryFromBufferLayer:function(){var a=null;0<this.bufferLayer.graphics.length&&(a=this.bufferLayer.graphics[0].geometry);return a},_onDrawBoxClear:function(){this._clearBufferLayer()},_onDrawEnd:function(){this._updateBuffer()},_clearBufferLayer:function(){this.bufferLayer&&
this.bufferLayer.clear()},_updateBuffer:function(){this._clearBufferLayer();this.execute()},destroy:function(){this.bufferLayer&&this.map.removeLayer(this.bufferLayer);this.bufferLayer=null;this.inherited(arguments)}})});