// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
require({cache:{"esri/dijit/LocateButton":function(){define("require dojo/Evented dojo/_base/declare dojo/_base/lang dojo/has ../kernel ../config dijit/_WidgetBase dijit/a11yclick dijit/_TemplatedMixin dojo/on dojo/Deferred dojo/text!./templates/LocateButton.html dojo/i18n!../nls/jsapi dojo/dom-class dojo/dom-style dojo/dom-attr ../geometry/webMercatorUtils ../geometry/Point ../SpatialReference ../graphic ../symbols/PictureMarkerSymbol ../tasks/ProjectParameters".split(" "),function(g,p,r,f,t,h,n,
k,m,u,e,a,d,c,q,w,v,x,y,z,A,B,C){g=r("esri.dijit.LocateButton",[k,u,p],{templateString:d,options:{theme:"LocateButton",map:null,visible:!0,highlightLocation:!0,symbol:new B(g.toUrl("./images/sdk_gps_location.png"),28,28),infoTemplate:null,scale:null,useTracking:!1,clearOnTrackingStop:!1,setScale:!0,centerAt:!0,timeout:15E3,graphicsLayer:null,geolocationOptions:{maximumAge:0,timeout:15E3,enableHighAccuracy:!0}},constructor:function(b,a){b=f.mixin({},this.options,b);this.domNode=a;this._i18n=c;a=navigator.geolocation;
var l=window.hasOwnProperty("isSecureContext"),l=l&&window.isSecureContext||!l&&"https:"===window.location.protocol;l&&a||(b.visible=!1);a||console.log("LocateButton::navigator.geolocation unsupported.");l||console.log("LocateButton::navigator.geolocation requires a secure origin.");this.set("map",b.map);this.set("theme",b.theme);this.set("visible",b.visible);this.set("scale",b.scale);this.set("highlightLocation",b.highlightLocation);this.set("symbol",b.symbol);this.set("infoTemplate",b.infoTemplate);
this.set("geolocationOptions",b.geolocationOptions);this.set("useTracking",b.useTracking);this.set("setScale",b.setScale);this.set("centerAt",b.centerAt);this.set("timeout",b.timeout);this.set("graphicsLayer",b.graphicsLayer);this.set("clearOnTrackingStop",b.clearOnTrackingStop);this.watch("theme",this._updateThemeWatch);this.watch("visible",this._visible);this.watch("tracking",this._locate);this.watch("useTracking",f.hitch(this,function(){this.get("tracking")&&!this.get("useTracking")&&this._stopTracking();
this._setTitle()}));this._css={container:"locateContainer",locate:"zoomLocateButton",loading:"loading",tracking:"tracking"}},postCreate:function(){this.inherited(arguments);this.own(e(this._locateNode,m,f.hitch(this,this.locate)))},startup:function(){this.inherited(arguments);this.get("map")||(this.set("visible",!1),console.log("LocateButton::map required"));if(this.get("map").loaded)this._init();else e.once(this.get("map"),"load",f.hitch(this,function(){this._init()}))},destroy:function(){this.clear();
this._graphicsEvent&&this._graphicsEvent.remove();this._removeWatchPosition();this.inherited(arguments)},clear:function(){var b=this.get("highlightGraphic"),a=this.get("graphicsLayer");b&&(a?a.remove(b):this.get("map").graphics.remove(b),this.set("highlightGraphic",null))},locate:function(){this.get("useTracking")&&this.set("tracking",!this.get("tracking"));return this._locate()},show:function(){this.set("visible",!0)},hide:function(){this.set("visible",!1)},_setTitle:function(){this.get("useTracking")?
this.get("tracking")?v.set(this._locateNode,"title",this._i18n.widgets.locateButton.locate.stopTracking):v.set(this._locateNode,"title",this._i18n.widgets.locateButton.locate.tracking):v.set(this._locateNode,"title",this._i18n.widgets.locateButton.locate.title)},_removeWatchPosition:function(){this.get("watchId")&&(navigator.geolocation.clearWatch(this.get("watchId")),this.set("watchId",null));this._removePrivateVars()},_stopTracking:function(){q.remove(this._locateNode,this._css.tracking);this._removeWatchPosition();
this.get("clearOnTrackingStop")&&this.clear();this._hideLoading()},_positionToObject:function(b){return b?{coords:f.mixin({},b.coords),timestamp:b.timestamp}:{}},_startTracking:function(){q.add(this._locateNode,this._css.tracking);this._removeWatchPosition();var b=navigator.geolocation.watchPosition(f.hitch(this,function(b){b=this._positionToObject(b);this._setPosition(b).then(f.hitch(this,function(b){this._locateEvent(b)}),f.hitch(this,function(b){b||(b=Error("LocateButton::Error setting the position."));
this._locateError(b)}))}),f.hitch(this,function(b){this.set("tracking",!1);b||(b=Error("LocateButton::Could not get tracking position."));this._locateError(b)}),this.get("geolocationOptions"));this.set("watchId",b)},_removePrivateVars:function(){this._scale=this._position=this._graphic=null},_getCurrentPosition:function(){var b=new a;this._removePrivateVars();var l=setTimeout(f.hitch(this,function(){clearTimeout(l);b.reject(Error("LocateButton::time expired for getting location."))}),this.get("timeout"));
navigator.geolocation.getCurrentPosition(f.hitch(this,function(a){a=this._positionToObject(a);clearTimeout(l);this._setPosition(a).then(f.hitch(this,function(a){b.resolve(a)}),f.hitch(this,function(a){a||(a=Error("LocateButton::Error setting map position."));b.reject(a)}))}),f.hitch(this,function(a){a||(a=Error("LocateButton::Could not get current position."));b.reject(a)}),this.get("geolocationOptions"));return b.promise},_locate:function(){var b=new a;this._showLoading();if(navigator.geolocation)this.get("useTracking")?
this.get("tracking")?(this._startTracking(),b.resolve({tracking:!0})):(this._stopTracking(),b.resolve({tracking:!1})):this._getCurrentPosition().then(f.hitch(this,function(a){this._locateEvent(a);b.resolve(a)}),f.hitch(this,function(a){a||(a=Error("LocateButton::Could not get current position."));this._locateError(a);b.reject(a)}));else{var l=Error("LocateButton::geolocation unsupported");this._locateError(l);b.reject(l)}this._setTitle();return b.promise},_projectPoint:function(b){var l=new a,d=this.get("map").spatialReference,
c=d.wkid;d.isWebMercator()?(b=x.geographicToWebMercator(b),l.resolve(b)):n.defaults.geometryService&&4326!==c?(c=new C,c.geometries=[b],c.outSR=d,n.defaults.geometryService.project(c).then(f.hitch(this,function(a){a&&a.length?l.resolve(a[0]):l.reject(Error("LocateButton::Point was not projected."))}),function(a){a||(a=Error("LocateButton::please specify a geometry service on esri/config to project."));l.reject(a)})):l.resolve(b);return l.promise},_getScale:function(a){var b=this.get("scale");return a&&
a.coords?b||a.coords.accuracy||5E4:b||5E4},_createPoint:function(a){var b;a&&a.coords&&(b=new y([a.coords.longitude,a.coords.latitude],new z({wkid:4326})));return b},_setPosition:function(b){var d=new a,c,e;this._removePrivateVars();if((this._position=b)&&b.coords){if(c=this._createPoint(b))this._graphic=e=this._createGraphic(c,b);var q=this._getScale(b);this._scale=q;c?this._projectPoint(c).then(f.hitch(this,function(a){this._graphic=e=this._createGraphic(a,b);var c={graphic:e,scale:q,position:b};
this.get("setScale")&&this.get("map").setScale(q);this.get("centerAt")?this.get("map").centerAt(a).then(f.hitch(this,function(){d.resolve(c)}),f.hitch(this,function(a){a||(a=Error("LocateButton::Could not center map."));d.reject(a)})):d.resolve(c)}),f.hitch(this,function(a){a||(a=Error("LocateButton::Error projecting point."));d.reject(a)})):(c=Error("LocateButton::Invalid point"),d.reject(c))}else c=Error("LocateButton::Invalid position"),d.reject(c);return d.promise},_createGraphic:function(a,c){var b;
a&&(c={position:c},b=new A(a,this.get("symbol"),c,this.get("infoTemplate")));return b},_locateEvent:function(a){if(a.graphic){var b=this.get("highlightGraphic"),c=this.get("graphicsLayer");b?(b.setGeometry(a.graphic.geometry),b.setAttributes(a.graphic.attributes),b.setInfoTemplate(a.graphic.infoTemplate),b.setSymbol(a.graphic.symbol)):(b=a.graphic,this.get("highlightLocation")&&(c?c.add(b):this.get("map").graphics.add(b)));this.set("highlightGraphic",b)}this._hideLoading();this.emit("locate",a)},
_locateError:function(a){a={graphic:this._graphic,scale:this._scale,position:this._position,error:a};this._hideLoading();this.emit("locate",a)},_showLoading:function(){this.get("useTracking")||q.add(this._locateNode,this._css.loading)},_hideLoading:function(){this.get("useTracking")||q.remove(this._locateNode,this._css.loading)},_init:function(){this._visible();this._setTitle();this.get("tracking")&&this.get("useTracking")&&this._locate();this.set("loaded",!0);this.emit("load",{})},_updateThemeWatch:function(a,
c,d){q.remove(this.domNode,c);q.add(this.domNode,d)},_visible:function(){this.get("visible")?w.set(this.domNode,"display","block"):w.set(this.domNode,"display","none")}});t("extend-esri")&&f.setObject("dijit.LocateButton",g,h);return g})},"widgets/MyLocation/Compass":function(){define("dojo/_base/declare dojo/_base/lang jimu/BaseWidget dojo/on esri/symbols/PictureMarkerSymbol esri/symbols/SimpleFillSymbol esri/symbols/SimpleLineSymbol esri/graphic esri/Color esri/geometry/Circle".split(" "),function(g,
p,r,f,t,h,n,k,m,u){var e=null,a;a=g([r],{constructor:function(a,c,e){this.id="widget-myLocation-compass-"+(new Date).getTime();this.map=c;this.folderUrl=a;this.config=e;this._debug=0;this.inherited(arguments)},show:function(a,c){if(this.map.spatialReference.isWebMercator()||4326===this.map.spatialReference)!0===this.config.useCompass&&this._showDirection(c),!0===this.config.useAccCircle&&this._showAccCircle(a,c)},_showDirection:function(a){if(a.useTracking){this._destroyDirectionHandler();var c;"ondeviceorientationabsolute"in
window?c="deviceorientationabsolute":"ondeviceorientation"in window&&(c="deviceorientation");this._directionHandler=f(window,c,p.hitch(this,this._watchMobileLocation,a))}},_watchMobileLocation:function(a,c){if(c){var d;c.absolute&&null!==c.alpha&&"undefined"!==typeof c.alpha?d=c.alpha:c.webkitCompassHeading?d=360-c.webkitCompassHeading:(console.log("Could not retrieve absolute orientation"),this._debug&&(d=0));this._debug&&(document.querySelector(".jimu-title").innerText=this._flag1+this._flag2+"_alpha\x3d"+
d);"undefined"!==typeof d&&a.highlightGraphic.setSymbol(new t({url:this.folderUrl+"/images/compass.png",width:36,height:36,angle:d}))}},_showAccCircle:function(a,c){this._destroyAccCircle();if((c=c.highlightGraphic)&&c._graphicsLayer){var d=c.geometry;a=a.position.coords.accuracy/this.map.getResolution();a=new u({center:d,radius:a});a=new k(a,new h(h.STYLE_SOLID,new n(n.STYLE_SOLID,new m([94,164,255,.2]),1),new m([16,119,255,.2])));c._graphicsLayer.add(a);this._accCircle=a;this._accCircleGraphicsLayer=
c._graphicsLayer}},clean:function(){this._destroyDirectionHandler();this._destroyAccCircle()},destroy:function(){this.clean();this.inherited(arguments)},_destroyDirectionHandler:function(){this._directionHandler&&(this._directionHandler.remove&&this._directionHandler.remove(),this._directionHandler=null)},_destroyAccCircle:function(){this._accCircleGraphicsLayer&&this._accCircleGraphicsLayer.remove&&this._accCircle&&(this._accCircleGraphicsLayer.remove(this._accCircle),this._accCircle=null)}});a.getInstance=
function(d,c,f){null===e&&(e=new a(d,c,f));return e};return a})},"esri/geometry/Circle":function(){define("dojo/_base/declare dojo/_base/lang dojo/has ../kernel ./Point ./Polygon ./geodesicUtils ./webMercatorUtils ../WKIDUnitConversion ../units".split(" "),function(g,p,r,f,t,h,n,k,m,u){g=g(h,{declaredClass:"esri.geometry.Circle",_unitToMeters:{esriCentimeters:.01,esriDecimeters:.1,esriFeet:.3048,esriInches:.0254,esriKilometers:1E3,esriMeters:1,esriMiles:1609.344,esriMillimeters:.001,esriNauticalMiles:1852,
esriYards:.9144,esriDecimalDegrees:111320},constructor:function(e,a){e.center?a=e:(a=a||{},a.center=e);this.center=p.isArray(a.center)?new t(a.center[0],a.center[1]):a.center;this.radius=a.radius||1E3;this.radiusUnit=a.radiusUnit||u.METERS;this.geodesic=!0===a.geodesic?!0:!1;this.numberOfPoints=a.numberOfPoints||60;this._init()},toJson:function(){return this.inherited(arguments)},_init:function(){this.rings=[];this._ring=0;var e=this.radius*this._unitToMeters[this.radiusUnit],a=this._srType(this.center.spatialReference);
if(this.geodesic){var d;switch(a){case "webMercator":d=k.webMercatorToGeographic(this.center);break;case "projected":console.error("Creating a geodesic circle requires the center to be specified in web mercator or geographic coordinate system");break;case "geographic":d=this.center}e=this._createGeodesicCircle(d,e,this.numberOfPoints,d.spatialReference);"webMercator"===a&&(e=k.geographicToWebMercator(e))}else{var c;"webMercator"===a||"projected"===a?c=e/this._convert2Meters(1,this.center.spatialReference):
"geographic"===a&&(c=e/this._unitToMeters.esriDecimalDegrees);e=this._createPlanarCircle(this.center,c,this.numberOfPoints)}this.spatialReference=e.spatialReference;this.addRing(e.rings[0]);this.verifySR()},_createGeodesicCircle:function(e,a,d,c){for(var f=0,g=Math.PI/180,k=[],m;f<2*Math.PI;)m=n._directGeodeticSolver(e.y*g,e.x*g,f,a,c),k.push([m.x,m.y]),f+=Math.PI/(d/2);k.push(k[0]);return new h(k)},_createPlanarCircle:function(e,a,d){for(var c=0,f=[],g,k;c<2*Math.PI;)g=e.x+Math.cos(c)*a,k=e.y+Math.sin(c)*
a,f.push([g,k]),c+=Math.PI/(d/2);f.push(f[0]);e=new h(e.spatialReference);e.addRing(f);return e},_srType:function(e){return e.isWebMercator()?"webMercator":null!=m[e.wkid]||e.wkt&&0===e.wkt.indexOf("PROJCS")?"projected":"geographic"},_convert2Meters:function(e,a){if(null!=m[a.wkid])a=m.values[m[a.wkid]];else{a=a.wkt;var d=a.lastIndexOf(",")+1,c=a.lastIndexOf("]]");a=parseFloat(a.substring(d,c))}return e*a}});r("extend-esri")&&p.setObject("geometry.Circle",g,f);return g})},"widgets/MyLocation/a11y/Widget":function(){define(["dojo/_base/lang",
"dojo/on","dojo/_base/html","dijit/a11yclick"],function(g,p,r,f){return{a11y_updateLabel:function(f){f&&r.setAttr(this.domNode,"aria-label",f)},a11y_initEvents:function(){this.own(p(this.domNode,f,g.hitch(this,this.onLocationClick)))}}})},"widgets/MyLocation/_build-generate_module":function(){define(["dojo/text!./css/style.css","dojo/i18n!./nls/strings"],function(){})},"url:esri/dijit/templates/LocateButton.html":'\x3cdiv class\x3d"${theme}" role\x3d"presentation"\x3e\r\n    \x3cdiv class\x3d"${_css.container}"\x3e\r\n            \x3cdiv data-dojo-attach-point\x3d"_locateNode" role\x3d"button" class\x3d"${_css.locate}" tabindex\x3d"0"\x3e\x3cspan\x3e${_i18n.widgets.locateButton.locate.button}\x3c/span\x3e\x3c/div\x3e\r\n    \x3c/div\x3e\r\n\x3c/div\x3e\r\n',
"url:widgets/MyLocation/css/style.css":'.jimu-widget-mylocation{border-radius: 5px; background-color: #555; border: 1px solid #999;}.jimu-widget-mylocation.onCenter {background-color: #000;}.jimu-widget-mylocation .place-holder {padding: 2px; width: 30px; height: 30px; background-color: #555; -webkit-user-select: none; -moz-user-select: none; -ms-user-select: none; user-select: none; cursor: pointer; -webkit-border-radius: 5px; -moz-border-radius: 5px; -o-border-radius: 5px; border-radius: 5px; background-image: url("images/locate.png"); background-position: center center; background-repeat: no-repeat;}.jimu-widget-mylocation .place-holder.locating{background-image: url("images/loading.gif");}.jimu-widget-mylocation .place-holder.tracking{background-image: url("images/stop.png") !important; background-color: #000;}.jimu-widget-mylocation .place-holder.nohttps{background-image: url("images/locate_disabled.png") !important;}.jimu-widget-mylocation .place-holder.nohttps:hover{background-color: #555;}.jimu-widget-mylocation .place-holder.nohttps,.jimu-widget-mylocation .place-holder{background-color: #555;}.jimu-widget-mylocation.onLocate .place-holder{background-color: rgba(0,0,0,0.4);}.jimu-widget-mylocation.onCenter .place-holder{background-color: #000;}.jimu-widget-mylocation .place-holder:hover{background-color: #333;}',
"*now":function(g){g(['dojo/i18n!*preload*widgets/MyLocation/nls/Widget*["ar","bs","ca","cs","da","de","en","el","es","et","fi","fr","he","hi","hr","hu","id","it","ja","ko","lt","lv","nb","nl","pl","pt-br","pt-pt","ro","ru","sl","sr","sv","th","tr","zh-cn","uk","vi","zh-hk","zh-tw","ROOT"]'])},"*noref":1}});
define("dojo/_base/declare dojo/Deferred esri/layers/GraphicsLayer jimu/BaseWidget esri/dijit/LocateButton dojo/_base/html dojo/on dojo/_base/lang jimu/utils ./Compass ./a11y/Widget jimu/dijit/Message dojo/touch".split(" "),function(g,p,r,f,t,h,n,k,m,u,e){g=g([f],{name:"MyLocation",baseClass:"jimu-widget-mylocation",moveTopOnActive:!1,_DEBUG:!1,_graphicsLayer:null,startup:function(){this.inherited(arguments);this.a11y_updateLabel(this.nls._widgetLabel);this.placehoder=h.create("div",{"class":"place-holder",
title:this.label},this.domNode);this.isNeedHttpsButNot=m.isNeedHttpsButNot();!0===this.isNeedHttpsButNot?(console.log("LocateButton::navigator.geolocation requires a secure origin."),h.addClass(this.placehoder,"nohttps"),h.setAttr(this.placehoder,"title",this.nls.httpNotSupportError)):window.navigator.geolocation?(this.own(n(this.placehoder,"click",k.hitch(this,this.onLocationClick))),this.own(n(this.map,"zoom-end",k.hitch(this,this._scaleChangeHandler))),this.a11y_initEvents()):h.setAttr(this.placehoder,
"title",this.nls.browserError)},onLocationClick:function(a){a&&a.stopPropagation&&a.stopPropagation();h.hasClass(this.domNode,"onCenter")||h.hasClass(this.domNode,"locating")?this.geoLocate&&!0===this.geoLocate._canDestroy?(this._destroyGeoLocate(),this._tryToCleanCompass()):this._DEBUG&&console.log("\x3d\x3d\x3eblock click1"):!this.geoLocate||this.geoLocate&&!0===this.geoLocate._canDestroy?(this._destroyGeoLocate(),this._createGeoLocateAndLocate()):this._DEBUG&&console.log("\x3d\x3d\x3eblock click2")},
_createGeoLocateAndLocate:function(){this._DEBUG&&console.log("\x3d\x3d\x3e_createGeoLocateAndLocate");this.getGeoLocateInstance().then(k.hitch(this,function(){this.geoLocate.locate();h.addClass(this.placehoder,"locating")}))},getGeoLocateInstance:function(){var a=new p;this.geoLocate&&a.resolve(this.geoLocate);var d=this.config.locateButton;d.map=this.map;"undefined"===typeof this.config.locateButton.useTracking&&(d.useTracking=!0);d.centerAt=!0;d.setScale=!0;var c={maximumAge:0,timeout:15E3,enableHighAccuracy:!0};
d.geolocationOptions&&(d.geolocationOptions=k.mixin(c,d.geolocationOptions));11===m.has("ie")&&(d.geolocationOptions.maximumAge=300,d.geolocationOptions.enableHighAccuracy=!1);this._graphicsLayer||(this._graphicsLayer=new r,this.map.addLayer(this._graphicsLayer));d.graphicsLayer=this._graphicsLayer;this.geoLocate=new t(d);this.geoLocate.own(n(this.geoLocate,"load",k.hitch(this,function(){a.resolve(this.geoLocate)})));this.geoLocate.own(n(this.geoLocate,"locate",k.hitch(this,this.onLocateOrError)));
this.geoLocate.startup();return a},onLocateOrError:function(a){this.geoLocate&&setTimeout(k.hitch(this,function(){this.geoLocate._canDestroy=!0;if(a.error)this.onLocateError(a);else this.onLocate(a)}),300)},onLocate:function(a){h.removeClass(this.placehoder,"locating");this.geoLocate.useTracking&&h.addClass(this.placehoder,"tracking");if(a.error)this.onLocateError(a);else h.addClass(this.domNode,"onCenter"),this.neverLocate=!1,this._tryToShowCompass(a)},onLocateError:function(a){console.error(a.error);
this._tryToCleanCompass();h.removeClass(this.placehoder,"locating");h.removeClass(this.domNode,"onCenter");h.removeClass(this.placehoder,"tracking")},_scaleChangeHandler:function(){var a=this.map.getScale();a&&this.geoLocate&&this.geoLocate.useTracking&&(this.geoLocate.scale=a)},_tryToShowCompass:function(a){!0!==this.config.locateButton.highlightLocation||!0!==this.config.locateButton.useTracking||!0!==this.config.useCompass&&!0!==this.config.useAccCircle||(this.compass=u.getInstance({folderUrl:this.folderUrl,
map:this.map,config:this.config}),this.compass.show(a,this.geoLocate))},_tryToCleanCompass:function(){this.compass&&this.compass.clean&&this.compass.clean()},_tryToDestroyCompass:function(){this.compass&&this.compass.destroy&&this.compass.destroy()},_destroyGeoLocate:function(){this._DEBUG&&console.log("\x3d\x3d\x3e_destroyGeoLocate");this._graphicsLayer&&this._graphicsLayer.clear();this.geoLocate&&this.geoLocate._canDestroy&&(this.geoLocate&&(this.geoLocate.clear(),this.geoLocate.destroy(),this.geoLocate=
null),h.removeClass(this.domNode,"onCenter"),h.removeClass(this.placehoder,"tracking"))},destroy:function(){this._tryToCleanCompass();this._tryToDestroyCompass();this._destroyGeoLocate();this._graphicsLayer&&(this.map.removeLayer(this._graphicsLayer),this._graphicsLayer=null);this.inherited(arguments)}});g.inPanel=!1;g.hasUIFile=!1;g.extend(e);return g});