// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define("dojo/_base/declare dojo/Evented dojo/_base/array dojo/DeferredList dojo/Deferred dojo/_base/lang dojo/dom-class dojo/dom-construct dojo/on dojo/keys jimu/utils jimu/dijit/Message esri/graphic esri/layers/FeatureLayer esri/tasks/query ./analysisUtils".split(" "),function(C,D,z,u,v,p,q,r,x,y,w,A,E,t,B,n){return C("GroupedCountInfo",[D],{summaryLayer:null,summaryFields:[],summaryIds:[],summaryFeatures:[],tabNum:null,popupFields:[],groupedResults:{},specialFields:null,dateFields:{},symbolField:null,
graphicsLayer:null,lyrRenderer:null,lyrSymbol:null,featureCount:0,incidentCount:0,displayCount:!1,allFields:!1,configuredPopUpFields:[],constructor:function(a,d,b){this.tab=a;this.container=d;this.parent=b;this.config=b.config;this.graphicsLayer=null;this.specialFields={};this.typeIdField="";this.types=[];this.dateFields={};this.baseLabel=""!==a.label?a.label:a.layerTitle?a.layerTitle:a.layers;this.parentNode=b.domNode},queryTabCount:function(a,d,b,g){var c=new v;this.displayCount=g;this.incidentCount=
a.length;var e=[this.tab.tabLayers[0]];this.mapServiceLayer&&1<this.tab.tabLayers.length&&(e=[this.tab.tabLayers[1]]);if(0<this.tab.tabLayers.length&&this.tab.tabLayers[0].url&&-1<this.tab.tabLayers[0].url.indexOf("MapServer")){this.mapServiceLayer=!0;var f;"undefined"!==typeof this.tab.tabLayers[0].infoTemplate?(this.summaryLayer=this.tab.tabLayers[0],this.summaryLayer.hasOwnProperty("loaded")&&this.summaryLayer.loaded?(this.summaryFields=this._getFields(this.summaryLayer),this._performQuery(a,d,
b,g,e).then(function(a){c.resolve(a)})):(f=new t(this.summaryLayer.url),f.infoTemplate=this.tab.tabLayers[0].infoTemplate,e=[f],this.tab.tabLayers=e,x(f,"load",p.hitch(this,function(){this.summaryLayer=f;this.summaryFields=this._getFields(this.summaryLayer);this._performQuery(a,d,b,g,e).then(function(a){c.resolve(a)})})))):this.loading||(f=new t(this.tab.tabLayers[0].url),this.loading=!0,x(f,"load",p.hitch(this,function(){this.summaryLayer=f;this.summaryFields=this._getFields(this.summaryLayer);for(var k=
this.tab.tabLayers[0].url.split("MapServer/")[1],m=this.parent.map.itemInfo.itemData.operationalLayers,l=0;l<m.length;l++){var h=m[l];if(-1<this.tab.tabLayers[0].url.indexOf(h.url)&&"undefined"!==typeof h.layerObject)if(h.layerObject.infoTemplates){if(h=h.layerObject.infoTemplates[k]){f.infoTemplate=h.infoTemplate;break}}else if(h.layerObject.infoTemplate){f.infoTemplate=h.layerObject.infoTemplate;break}}e=[f];this.tab.tabLayers=e;this.loading=!1;this._performQuery(a,d,b,g,e).then(function(a){c.resolve(a)})})))}this.mapServiceLayer||
this._performQuery(a,d,b,g,e).then(function(a){c.resolve(a)});return c},_performQuery:function(a,d,b,g,c){var e=new v,f=[],k,m;0<d.length?m=n.getGeoms(d):0<a.length&&(m=n.getGeoms(a));this.summaryGeoms=m;if(0<m.length)for(a=0;a<m.length;a++)f=m[a],d=n.createDefArray(c,f,this.parent.opLayers,this.tab),k=0===a?f=d:f=k.concat(d);(new u(f)).then(p.hitch(this,function(a){for(var d=0,f=0;f<a.length;f++){var c=a[f][1];isNaN(c)?c&&c.features?d+=c.features.length:c&&"undefined"!==typeof c.length&&(d+=c.length):
d+=c}this.updateTabCount(d,b,g);this.queryOnLoad&&p.hitch(this,this._queryFeatures(this.summaryGeoms));e.resolve(d)}));return e},updateTabCount:function(a,d,b){this.displayCount=b;this.featureCount=a;n.updateTabCount(this.featureCount,d,b,this.baseLabel,this.incidentCount)},updateForIncident:function(a,d,b,g,c,e,f){this.incidentCount=a.length;this.allFields="undefined"!==typeof e&&"undefined"!==typeof f?e?!0:f:!1;var k="undefined"!==typeof c,m;this.tabNum=g;k?m=new v:(this.container.innerHTML="",
q.add(this.container,"loading"));this.summaryIds=[];this.summaryFeatures=[];this.groupedResults={};if(0<this.tab.tabLayers.length){var l=[];if(0<d.length)l=d;else for(d=0;d<a.length;d++)g=a[d].geometry?a[d].geometry:a[d],"polygon"===g.type&&l.push(g);var h;"undefined"!==typeof this.tab.tabLayers[0].infoTemplate?(this.summaryLayer=this.tab.tabLayers[0],h=new t(this.summaryLayer.url),h.infoTemplate=this.tab.tabLayers[0].infoTemplate,this.tab.tabLayers[1]=h,this.summaryFields=this._getFields(this.tab.tabLayers[0]),
this.configuredPopUpFields=n.getPopupConfiguredFields(this.tab.tabLayers[0]),k?this._queryFeatures(l,k).then(function(a){m.resolve(a)}):(this._initGraphicsLayer(b),p.hitch(this,this._queryFeatures(l)))):(h=new t(this.tab.tabLayers[0].url),x(h,"load",p.hitch(this,function(){this.summaryLayer=h;if(-1<this.tab.tabLayers[0].url.indexOf("MapServer"))for(var a=this.tab.tabLayers[0].url.split("MapServer/")[1],d=this.parent.map.itemInfo.itemData.operationalLayers,c=0;c<d.length;c++){var e=d[c];if(-1<this.tab.tabLayers[0].url.indexOf(e.url)&&
"undefined"!==typeof e.layerObject&&e.layerObject.infoTemplates&&(e=e.layerObject.infoTemplates[a])){h.infoTemplate=e.infoTemplate;break}}this.tab.tabLayers[1]=h;this.summaryLayer=this.tab.tabLayers[1];this.summaryFields=this._getFields(this.tab.tabLayers[1]);this.configuredPopUpFields=n.getPopupConfiguredFields(this.tab.tabLayers[1]);k?this._queryFeatures(l,k).then(function(a){m.resolve(a)}):(this._initGraphicsLayer(b),p.hitch(this,this._queryFeatures(l)))})));if(k)return m}},_initGraphicsLayer:function(a){null!==
a&&(this.graphicsLayer=a,this.graphicsLayer.clear(),this.summaryLayer&&this.summaryLayer.renderer&&(this.lyrRenderer=this.summaryLayer.renderer,this.graphicsLayer.renderer=this.lyrRenderer,"undefined"!==typeof this.summaryLayer.renderer.attributeField?this.symbolField=this.summaryLayer.renderer.attributeField:this.lyrSymbol=this.lyrRenderer.symbol))},_queryFeatures:function(a,d){var b;d&&(b=new v);for(var g=[],c=-1===[null,void 0,""].indexOf(this.tab.tabLayers[0].id)?this.tab.tabLayers[0].id:this.tab.layers,
c=n.getFilter(c,this.parent.opLayers),e=new B,f=0;f<a.length;f++)e.geometry=a[f],e.where=c,g.push(this.summaryLayer.queryIds(e));(new u(g)).then(p.hitch(this,function(a){for(var c,e,f=0;f<a.length;f++)a[f][0]&&(c=a[f][1],e=c=0===f?c:e.concat(c));c?(this.summaryIds=c,0<this.summaryIds.length?d?this._queryFeaturesByIds(d).then(function(a){b.resolve(a)}):this._queryFeaturesByIds():d||this._processResults()):d||this._processResults()}),p.hitch(this,function(a){console.error(a);new A({message:a})}));if(d)return b},
_queryFeaturesByIds:function(a){var d,b=[];a&&(d=new v);var g=this.summaryLayer.maxRecordCount||1E3,c=this.summaryIds.slice(0,g);this.summaryIds.splice(0,g);var e=new B,f=-1===[null,void 0,""].indexOf(this.summaryLayer.id)?this.summaryLayer.id:this.tab.layers;e.where=n.getFilter(f,this.parent.opLayers);var k=!1;z.some(this.summaryFields,p.hitch(this,function(a){if("area"===a.type||"length"===a.type||this.graphicsLayer)return k=!0}));a&&(k=!0);this.summaryLayer.supportsAdvancedQueries&&(e.orderByFields=
[this.summaryFields[0].field]);e.returnGeometry=k;e.outSpatialReference=this.parent.map.spatialReference;e.outFields=["*"];e.objectIds=c;for(b.push(this.summaryLayer.queryFeatures(e));0<this.summaryIds.length;)c=this.summaryIds.slice(0,g),this.summaryIds.splice(0,g),e.objectIds=c,b.push(this.summaryLayer.queryFeatures(e));(new u(b)).then(p.hitch(this,function(b){this.summaryFeatures=[];for(var c=0;c<b.length;c++)if(b[c][0]){var e=b[c][1];e.features&&(this.summaryFeatures=this.summaryFeatures.concat(e.features))}a?
this._processResults(a).then(p.hitch(this,function(a){this.SA_SAT_download&&q.replace(this.SA_SAT_download,"download","processing");d.resolve(a)})):(this._processResults(),this.SA_SAT_download&&q.replace(this.SA_SAT_download,"download","processing"));this.SA_SAT_download&&q.replace(this.SA_SAT_download,"download","processing")}),p.hitch(this,function(a){console.error(a);new A({message:a})}));if(a)return d},_prepGroupedResults:function(){for(var a=0;a<this.summaryFeatures.length;a++){var d=this.summaryFeatures[a];
if("undefined"!==typeof this.summaryFields&&0<this.summaryFields.length){var b=n.getFieldValue(this.summaryFields[0].field,d.attributes[this.summaryFields[0].field],this.specialFields,this.dateFields,"longMonthDayYear",this.typeIdField,this.types,this.layerObject&&this.layerObject.renderer?this.layerObject:this.layerDefinition,d.attributes),b="undefined"!==typeof b&&null!==b?w.stripHTML(b.toString()):"";b in this.groupedResults?this.groupedResults[b].features.push(d):this.groupedResults[b]={features:[d]}}}},
_prepResults:function(){for(var a in this.groupedResults){var d=this.summaryFields[0];d.total=this.groupedResults[a].features.length;this.groupedResults[a].total=d.total;this.groupedResults[a].type=d.type;this.groupedResults[a].label=d.alias}},_processResults:function(a){this._prepGroupedResults();this._prepResults();var d=this.groupedResults,b=0,g,c;if(a)c=new v;else{this.container.innerHTML="";q.remove(this.container,"loading");if(0===Object.keys(this.groupedResults).length){this.container.innerHTML=
this.parent.nls.noFeaturesFound;return}var e=Object.keys(this.groupedResults).length+1;g=r.create("div",{style:"width:"+220*e+"px;"},this.container);q.add(g,"SAT_tabPanelContent");e=r.create("div",{},g);q.add(e,"SATcolExport");q.add(e,this.parent.lightTheme?"lightThemeBorder":"darkThemeBorder");var f=r.create("div",{"data-dojo-attach-point":"SA_SAT_download",title:this.parent.nls.downloadCSV,tabindex:"0",role:"button","aria-label":this.parent.nls.downloadCSVdownloadCSV,"class":"grpSummaryDownLoadCSVButton"},
e);q.add(f,[this.parent.isBlackTheme?"btnExportBlack":"btnExport","download"]);f.focus();w.initFirstFocusNode(this.parentNode,f);w.initLastFocusNode(this.parentNode,f);x(f,"click",p.hitch(this,this._exportToCSV,d));x(f,"keydown",p.hitch(this,function(a){if(!a.shiftKey||a.keyCode!==y.TAB)if(a.keyCode===y.ENTER||a.keyCode===y.SPACE)this._exportToCSV(d,a),setTimeout(function(){f.focus()},500)}))}var k=Object.keys(d).sort(),e=[];this.displayCount&&e.push({total:this.featureCount,a:void 0,info:this.parent.nls.count,
c:void 0});for(var m in k){var b=k[m],l=d[b],h=w.stripHTML(b.toString()),b=l.total;isNaN(b)&&(b=0);var b=w.localizeNumber(b),n="pre"===l.type?l.label.trim():h,h="pre"===l.type?h:l.label.trim(),l=""!==l.label?"colGroupedSummary":"colSummary";if(a)e.push({total:b,a:n,info:""===h?n:h,c:l});else{var t=r.create("div",{"class":"SATcol"},g);q.add(t,this.parent.lightTheme?"lightThemeBorder":"darkThemeBorder");var u=r.create("div",{style:"max-height: 45px;"},t);r.create("div",{"class":"SATcolWrap",style:"max-height: 30px; overflow: hidden;",
innerHTML:n},u);r.create("div",{"class":"SATcolWrap",style:"max-height: 30px; overflow: hidden;",innerHTML:h},u);r.create("div",{"class":l,innerHTML:b},t)}}m=[];g=null!==this.graphicsLayer;!a&&g&&(this.graphicsLayer.clear(),this.tab.tabLayers[1]&&this.tab.tabLayers[1].clear());if(this.summaryFeatures)for(k=0;k<this.summaryFeatures.length;k++)b=this.summaryFeatures[k],this.lyrSymbol?b.symbol=this.lyrSymbol:this.graphicsLayer?this.graphicsLayer.renderer&&(n=this.graphicsLayer.renderer.getSymbol(b),
b.symbol=n):this.summaryLayer.renderer&&this.summaryLayer.renderer.getSymbol&&(b.symbol=this.summaryLayer.renderer.getSymbol(b)),b=b.toJson?new E(b.toJson()):b,!a&&g?(this.graphicsLayer.add(b),this.tab.tabLayers[1].add(b)):m.push(b);!a&&g&&(this.graphicsLayer.setVisibility(!0),this.parent._toggleTabLayersNew(this.tabNum),this.tab.retsore&&this.emit("summary-complete",{bubbles:!0,cancelable:!0,tab:this.tabNum}));if(a)return c.resolve({graphics:m,analysisResults:e,context:this}),c},_exportToCSV:function(a,
d,b,g){var c;this.parent.config.hasOwnProperty("exportFieldsOptionForCSV")?c=this.parent.config.exportFieldsOptionForCSV:this.parent.config.hasOwnProperty("csvAllFields")&&(c=this.parent.config.csvAllFields);a=n.exportToCSV(this.summaryFeatures,d,b,g,{type:"grouped",baseLabel:this.baseLabel,csvAllFields:c,layer:this.summaryLayer,opLayers:this.parent.opLayers,nlsValue:this.parent.nls.groupedSummary,nlsCount:this.parent.nls.count,summaryFields:this.summaryFields,allFields:this.allFields,configuredPopUpFields:this.configuredPopUpFields});
this.summaryLayer=a.summaryLayer;return a.details},_getFields:function(a){this.layerDefinition=w.getFeatureLayerDefinition(a);this.layerObject=a;var d=n.getSkipFields(a),b,g=[];if("undefined"!==typeof this.tab.advStat){var c=this.tab.advStat.stats,e;for(e in c)0<c[e].length&&z.forEach(c[e],function(a){var c={field:a.expression,alias:a.label+"",type:e,total:0};b=a.expression;g.push(c)})}c=n.getSpecialFields(a);this.dateFields=c.dateFields;this.specialFields=c.specialFields;this.typeIdField=c.typeIdField;
this.types=c.types;if(this.allFields)for(c=0;c<a.fields.length;c++){var f=a.fields[c];-1===d.indexOf(f.name)&&b!==f.name&&g.push({field:f.name,alias:f.alias,type:f.type})}return g}})});