// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define("dojo/_base/array dojo/_base/declare dojo/_base/lang dojo/Deferred dojo/DeferredList esri/geometry/geometryEngineAsync esri/tasks/BufferParameters esri/tasks/GeometryService esri/tasks/query esri/tasks/QueryTask".split(" "),function(q,r,k,l,t,n,p,m,u,v){return r([],{constructor:function(a,d){this.map=a;this._geometryService=new m(d)},createUnionOfGeometries:function(a){var d;d=new l;if(!Array.isArray(a))return d.reject("No geometries to buffer"),d;n.union(a).then(k.hitch(this,function(a){a?
d.resolve(a):d.reject("Unioning failed")}),k.hitch(this,function(){d.reject("Unioning failed")}));return d},bufferGeometries:function(a,d){var c,b;c=new l;if(!Array.isArray(a))return c.reject("No geometries to buffer"),c;b=new p;b.bufferSpatialReference=this.map.spatialReference;b.distances=d;b.unionResults=!0;b.geodesic=!0;b.geometries=a;b.outSpatialReference=this.map.spatialReference;b.unit=m.UNIT_METER;this._geometryService.buffer(b,function(a){Array.isArray(a)&&0<a.length?c.resolve(a[0]):c.reject("Buffering failed")},
function(a){c.reject("Buffering failed: "+a)});return c},groupGeometriesByType:function(a){var d=[],c=[],b=[],e=[],f=[],g=new l;0<a.length?(q.forEach(a,k.hitch(this,function(a){"point"===a.type?(d.push(a),e.push(.2)):"polyline"===a.type?(c.push(a),f.push(.2)):"polygon"===a.type&&b.push(a)})),a=[],0<d.length&&a.push(this.bufferGeometries(d,e)),0<c.length&&a.push(this.bufferGeometries(c,f)),0<a.length?(new t(a)).then(k.hitch(this,function(a){if(0<a.length){for(var c=0;c<a.length;c++)b.push(a[c][1]);
g.resolve(b)}}),function(a){g.reject("Buffering point/line geometires failed: "+a)}):g.resolve(b)):g.resolve(a);return g},createBufferFromGeometries:function(a,d){var c,b,e;c=new l;if(!Array.isArray(a)||0>=a.length)return c.reject("No geometries to buffer"),c;this.groupGeometriesByType(a).then(k.hitch(this,function(a){b=d;n.union(a).then(k.hitch(this,function(a){a?0<b||"polygon"===a.type?(0===b&&(b=-.1),e=new p,e.bufferSpatialReference=this.map.spatialReference,e.distances=[b],e.geodesic=!0,e.geometries=
[a],e.outSpatialReference=this.map.spatialReference,e.unit=m.UNIT_METER,this._geometryService.buffer(e,function(a){Array.isArray(a)&&0<a.length?c.resolve(a[0]):c.reject("Buffering failed")},function(a){c.reject("Buffering failed: "+a)})):c.resolve(a):c.reject("Unioning failed")}),function(a){c.reject(a)})}));return c},findIntersectingFeatures:function(a,d,c,b,e){var f,g=new l,h={};d=new v(d);f=new u;a&&(f.geometry=a);f.returnGeometry=!0;f.outFields=c;b&&(f.where=b);e&&(f.outSpatialReference=e);d.execute(f,
k.hitch(this,function(c){c&&Array.isArray(c.features)&&0<c.features.length?n.union(this._getFeatureGeometries(c.features)).then(k.hitch(this,function(d){var b;Array.isArray(d.rings)&&0<d.rings.length?(b=new p,b.bufferSpatialReference=this.map.spatialReference,b.distances=[-.1],b.geodesic=!0,b.geometries=[d],b.outSpatialReference=this.map.spatialReference,b.unit=m.UNIT_METER,this._geometryService.buffer(b,function(b){Array.isArray(b)&&0<b.length?(h.intersectGeometry=a,h.features=c.features,h.highlight=
b[0],g.resolve(h)):g.reject("Buffering union failed")})):(h.intersectGeometry=a,h.features=c.features,h.highlight=d,g.resolve(h))})):(h.intersectGeometry=a,h.features=[],h.highlight=null,g.resolve(h))}),function(a){g.reject(a)});return g},find:function(a,d,c,b,e){var f=new l;this.findIntersectingFeatures(a,d,c,e).then(k.hitch(this,function(a){console.log(a.features.length+" "+b+" features found");f.resolve(a)}),function(a){f.reject(a)});return f},_getFeatureGeometries:function(a){return q.map(a,k.hitch(this,
function(a){return a.geometry}))}})});