// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
require({cache:{"url:widgets/CostAnalysis/setting/ReportSettings.html":'\x3cdiv class\x3d"esriCTMainConfigurationContainer"\x3e\r\n  \x3cdiv style\x3d"margin-bottom: 10px"\x3e\r\n      \x3cdiv class\x3d"esriCTReportNameLabel esriCTEllipsis"\x3e ${nls.generalSettings.reportSettings.reportNameLabel}\x3c/div\x3e\r\n      \x3cdiv style\x3d"width:70%" data-dojo-attach-point\x3d"reportNameNode" required\x3d"true" data-dojo-type\x3d"dijit/form/TextBox"\x3e\x3c/div\x3e\r\n  \x3c/div\x3e\r\n\r\n  \x3cdiv\x3e\r\n      \x3cdiv class\x3d"esriCTReportSettingsTable" data-dojo-attach-point\x3d"reportSettingsTableNode"\x3e\x3c/div\x3e\r\n  \x3c/div\x3e\r\n\r\n\x3c/div\x3e'}});
define("dojo/_base/declare jimu/dijit/Popup jimu/dijit/SimpleTable dijit/_WidgetBase dojo/Evented dijit/_TemplatedMixin dijit/_WidgetsInTemplateMixin dojo/text!./ReportSettings.html ../utils dojo/_base/array dojo/_base/lang jimu/dijit/Message dijit/form/TextBox".split(" "),function(h,k,l,m,n,p,q,r,g,f,c,t,u){return h([m,p,n,q],{templateString:r,popup:null,_reportSettingsTable:null,_tableTitleFields:{Layer:"layerName","Feature Template":"TEMPLATENAME",Geography:"GEOGRAPHY",Scenario:"SCENARIO",Count:"count",
Length:"Length",Area:"Area",Equation:"COSTEQUATION",Cost:"cost"},baseClass:"jimu-widget-cost-analysis-report-settings",constructor:function(a){c.mixin(this,a)},startup:function(){this._init()},postCreate:function(){this.popup=null;this.inherited(arguments)},_init:function(){this.isLoad?(this._addAbbreviationForTitle(),this._createDataForInitialLoad(),this.emit("onInitialLoad",this.previousReportSettings)):(this.previousReportSettings||(this._addAbbreviationForTitle(),this._createDataForInitialLoad()),
this._createReportSettingsTable(),this._createReportSettingsPopup())},_addAbbreviationForTitle:function(){var a,b;for(b in this._tableTitleFields)"Length"===b?(a=g.units[this.config.generalSettings.measurementUnit].lengthAbbr,this._tableTitleFields[b+" ("+a+")"]=this._tableTitleFields[b],delete this._tableTitleFields[b]):"Area"===b?(a=g.units[this.config.generalSettings.measurementUnit].areaAbbr,this._tableTitleFields[b+" ("+a+")"]=this._tableTitleFields[b],delete this._tableTitleFields[b]):"Cost"===
b&&(a=this.config.generalSettings.currency,this._tableTitleFields[b+" ("+a+")"]=this._tableTitleFields[b],delete this._tableTitleFields[b])},_createReportSettingsTable:function(){this.popup=new k({titleLabel:this.nls.generalSettings.reportSettings.reportSettingsPopupTitle,content:this.domNode,width:800,height:500,autoHeight:!0,"class":this.baseClass,buttons:[{label:this.nls.common.ok,onClick:c.hitch(this,function(){this.onOkButtonClicked()})},{label:this.nls.common.cancel}]})},onOkButtonClicked:function(){var a=
this._getReportSettings(),b,d=[];f.forEach(a.reportSettings,function(a){""!==a.columnLabel&&d.push(a.columnLabel)});b=d.filter(c.hitch(this,function(a,b,e){return e.indexOf(a)!==b}));0<b.length?new t({message:this.nls.generalSettings.reportSettings.duplicateMsg+":"+b[0]}):(this.emit("okButtonClicked",a),this.popup.close())},_createReportSettingsPopup:function(){this._reportSettingsTable=new l({fields:[{name:"showColumn",title:this.nls.generalSettings.reportSettings.checkboxLabel,type:"checkbox",editable:!1,
width:"15%"},{name:"columnTitle",title:this.nls.generalSettings.reportSettings.layerTitle,type:"text",editable:!1,width:"35%"},{name:"columnLabel",title:this.nls.generalSettings.reportSettings.columnLabel,width:"35%",type:"empty"},{name:"actions",title:this.nls.common.actions,width:"15%",type:"actions",actions:["up","down"]}],selectable:!1});this._reportSettingsTable.placeAt(this.reportSettingsTableNode);this._reportSettingsTable.startup();this.previousReportSettings.hasOwnProperty("reportName")&&
this.reportNameNode.set("value",this.previousReportSettings.reportName);this._populateReportSettings()},_createDataForInitialLoad:function(){this.previousReportSettings={};this.previousReportSettings.reportSettings=[];for(var a in this._tableTitleFields)this.previousReportSettings.reportSettings.push({isVisible:!0,columnTitle:a,columnLabel:"",fieldToMap:this._tableTitleFields[a]});this.previousReportSettings.reportName=""},_populateReportSettings:function(){f.forEach(this.previousReportSettings.reportSettings,
c.hitch(this,function(a){this._addNewRow(a)}))},_addNewRow:function(a){this._createRow(a)},_createRow:function(a){var b;b=this._reportSettingsTable.addRow({showColumn:a.isVisible,columnTitle:a.columnTitle});b.tr.labelTextBox=new u;b.tr.labelTextBox.set("value",a.columnLabel);b.tr.labelTextBox.placeAt(b.tr.cells[2])},_getReportSettings:function(){var a={},b,d;d=this._reportSettingsTable.getData();b=this._reportSettingsTable.getRows();a.reportSettings=[];f.forEach(d,c.hitch(this,function(c,d){var e=
{};e.isVisible=c.showColumn;e.columnTitle=c.columnTitle;e.columnLabel=b[d].labelTextBox.get("value");e.fieldToMap=this._getFieldTitleAbbr(c.columnTitle);a.reportSettings.push(e)}));a.reportName=this.reportNameNode.get("value");return a},_getFieldTitleAbbr:function(a){return-1<a.indexOf("Length")?"Length":-1<a.indexOf("Area")?"Area":-1<a.indexOf("Cost")?"cost":this._tableTitleFields[a]}})});