// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define("dojo/_base/lang dojo/_base/array jimu/LayerInfos/LayerInfos dojo/Deferred dojo/promise/all exports dojo/store/Observable dojo/store/Cache dojo/store/Memory esri/lang ./table/FeatureLayerQueryStore jimu/ArcadeUtils jimu/utils esri/graphic dojo/i18n!./nls/strings".split(" "),function(f,h,y,l,u,d,z,C,w,A,D,v,t,E,F){function G(a,b){if(!a||!a.length)return b||[];if(!b||!b.length)return a;for(var d=[],e=0,r=a.length;e<r;e++)for(var g=a[e],f=0,m=b.length;f<m;f++){var p=b[f];if(p.name===g.name){p.alias!==
g.alias&&(g.alias=p.alias);d.push(g);break}}return d}d.readLayerInfosObj=function(a){return y.getInstance(a,a.itemInfo)};d.readLayerInfosFromMap=function(a,b,d){var e=new l;y.getInstance(a,a.itemInfo).then(f.hitch(this,function(a){var g=[];b?a.traversalLayerInfosOfWebmap(function(a){g.push(a)}):a.traversal(function(a){g.push(a)});if(d){var c=[],f=a.getMapNotesLayerInfoArray();h.forEach(f,function(a){c.push(a.id);a.traversal(function(a){c.push(a.id)})});g=h.filter(g,function(a){return-1===c.indexOf(a.id)})}a=
a.getTableInfoArray();g=g.concat(a);e.resolve(g)}),f.hitch(this,function(a){console.error(a);e.reject(a)}));return e.promise};d.generateColumnsFromFields=function(a,b,c,e,r,g,H,m){function p(a){var b=a.name;if(q&&A.isDefined(q.fieldInfos))for(var e=0,d=q.fieldInfos.length;e<d;e++){var g=q.fieldInfos[e];if(g.fieldName===b&&g.format)return g.format}return(a=t.getDefaultPortalFieldInfo(a))&&a.format?a.format:null}var q=b.getPopupInfo()||b.getPopupInfoFromLayerObject&&b.getPopupInfoFromLayerObject(),
n={selectionHandle:{label:"",className:"selection-handle-column",hidden:!1,unhidable:!0,field:null,sortable:!1,_cache:{sortable:!1,statistics:!1},renderCell:function(a,b,e){e.setAttribute("role","button");e.setAttribute("title",F.selectionHandleLabel)}}};h.forEach(c,f.hitch(d,function(c,k,q){k="field"+k;var x=!!c.domain,l="esriFieldTypeDate"===c.type,u=e&&c.name===e,v="esriFieldTypeDouble"===c.type||"esriFieldTypeSingle"===c.type||"esriFieldTypeInteger"===c.type||"esriFieldTypeSmallInteger"===c.type,
y="esriFieldTypeString"===c.type,w=0===c.name.indexOf("expression/"),z=c.alias||c.name,B;B=1===q.length?!1:a&&a[k]?a[k].hidden:c?!c.show&&A.isDefined(c.show):!1;n[k]={label:z,className:k,hidden:B,unhidable:1===q.length?!1:!c.show&&A.isDefined(c.show)&&c._pk,field:c.name,sortable:!1,_cache:{sortable:!!g,statistics:H&&!x&&v}};y?n[k].formatter=f.hitch(d,d.urlFormatter):l?n[k].formatter=f.hitch(d,d.dateFormatter,p(c)):v&&(n[k].formatter=f.hitch(d,d.numberFormatter,p(c)));x?n[k].get=f.hitch(d,function(a,
b,c){return this.getCodeValue(a,b.name,c)},m,c):u?n[k].get=f.hitch(d,function(a,b,c){return this.getTypeName(c[a.name],b)},c,r):w?(q=this.arcade.getExpressionInfosFromLayerInfo(b),x=t.getFeatureLayerDefinition(m),n[k]._cache.sortable=!1,n[k].get=f.hitch(d,function(a,b,c,e){return this.arcade.getAttributes(e,a,c)[b.name]||""},q,c,x)):x||l||u||w||(n[k].get=f.hitch(d,function(a,b,c,e,g){var r=null;c&&e&&0<e.length&&(e=(e=h.filter(e,f.hitch(d,function(a){return a.id===g[c]})))&&e[0]||null)&&e.domains&&
e.domains[b.name]&&e.domains[b.name].codedValues&&(r=this.getCodeValue(a,b.name,g));return(a=null!==r?r:g[b.name])||isFinite(a)?a:""},m,c,e,r))}));return n};d.getTypeName=function(a,b){return t.fieldFormatter.getTypeName(a,b)};d.getCodeValue=function(a,b,c){return(a=t.getDisplayValueForCodedValueOrSubtype(a,b,c))&&a.isCodedValueOrSubtype?a.displayValue||"":""};d.urlFormatter=function(a){return t.fieldFormatter.getFormattedUrl(a)};d.dateFormatter=function(a,b){return t.fieldFormatter.getFormattedDate(b,
a)};d.numberFormatter=function(a,b){return t.fieldFormatter.getFormattedNumber(b,a)};d.readLayerObjectsFromMap=function(a,b,c){var e=new l,d=[];this.readLayerInfosFromMap(a,b,c).then(f.hitch(this,function(a){h.forEach(a,f.hitch(this,function(a){d.push(a.getLayerObject())}));u(d).then(f.hitch(this,function(a){e.resolve(a)}),f.hitch(this,function(a){e.reject(a);console.error(a)}))}),f.hitch(this,function(a){e.reject(a)}));return e.promise};d.readSupportTableInfoFromLayerInfos=function(a){var b=new l,
c=[];h.forEach(a,f.hitch(this,function(a){c.push(a.getSupportTableInfo())}));u(c).then(f.hitch(this,function(c){c=f.clone(c);h.forEach(c,function(b,c){b.id=a[c].id});b.resolve(c)}),function(a){b.reject(a)});return b.promise};d.readConfigLayerInfosFromMap=function(a,b,c){var e=new l,d=[];this.readLayerInfosFromMap(a,b,c).then(f.hitch(this,function(a){var b=[];h.forEach(a,function(a){d.push(a.getSupportTableInfo())});u(d).then(f.hitch(this,function(c){h.forEach(c,f.hitch(this,function(c,e){c.isSupportedLayer&&
(a[e].name=a[e].title,b.push(a[e]))}));e.resolve(b)}),f.hitch(this,function(a){e.reject(a)}))}),f.hitch(this,function(a){e.reject(a)}));return e.promise};d.getConfigInfosFromLayerInfos=function(a){return h.map(a,function(a){return d.getConfigInfoFromLayerInfo(a)})};d.getConfigInfoFromLayerInfo=function(a){var b={};b.name=a.name||a.title;b.id=a.id;b.show=a.isShowInMap();b.layer={url:a.getUrl()};var c=a.getPopupInfo();c&&!c.description&&(b.layer.fields=h.map(c.fieldInfos,function(a){return{name:a.fieldName,
alias:a.label,show:a.visible,format:a.format}}),a=f.getObject("layerObject.fields",!1,a),b.layer.fields=G(b.layer.fields,a),h.some(b.layer.fields,function(a){return a.show})||(b.layer.fields&&0<b.layer.fields.length?b.layer.fields[0].show=!0:console.warn("We do not get fields info.")));return b};d.generateCacheStore=function(a,b,c,e,d){a=new D({layer:a,objectIds:a._objectIds||null,totalCount:b,batchCount:c,where:e||"1\x3d1",spatialFilter:d});b=new w;return new C(a,b,{})};d.generateMemoryStore=function(a,
b){return new z(new w({data:a||[],idProperty:b}))};d.merge=function(a,b,c,e){for(var d=h.map(b,function(a){return a[c]}),f=0,l=a.length;f<l;f++){var m=d.indexOf(a[f][c]);-1<m&&e(a[f],b[m])}};d.syncOrderWith=function(a,b,c){function e(a,b){return h.map(a,function(a){return a[b]})}if(!f.isArray(b)||!c)return a;for(var d=e(a,c),g=[],l=0,m=b.length;l<m;l++){var p=d.indexOf(b[l][c]);-1<p&&(g=g.concat(a.splice(p,1)),d=e(a,c))}return g.concat(a)};d.arcade={};d.arcade.getExpressionInfosFromLayer=function(a,
b){a=v.readExprInfo.getArcadeProfilesByType(a,b,"infoTemplate");return 0<a.length&&a[0].expressionInfos?a[0].expressionInfos:[]};d.arcade.getExpressionInfosFromLayerInfo=function(a){return(a=a&&a.getPopupInfo())&&a.expressionInfos||[]};d.arcade.getAttributes=function(a,b,c){var d=new E(a.geometry,null,a);return v.customExpr.getAttributesFromCustomArcadeExpr(b,d,c)||a};d.arcade.appendArcadeExpressionsToFields=function(a,b){if(a){b=d.arcade.getExpressionInfosFromLayerInfo(b);if(0<b.length){var c=/^expression\//;
h.forEach(b,function(b){h.some(a,function(a){if(c.test(a.name))return a=a.name.substr(11),b.name===a})||a.push({name:"expression/"+b.name,alias:b.title,show:!0})})}return a}};d.arcade.isArcadeExpressionField=function(a){return a&&"string"===typeof a.name&&0===a.name.indexOf("expression/")};d.arcade.parseArcadeExpressions=function(a){return v.InfoTemplate._parseArcadeExpressions(a)};d.getSortbyFields=function(a,b){a=a&&a.get("sort")||[];b=b&&b.objectIdField;0<a.length?a=h.map(a,function(a){return a.attribute+
" "+(a.descending?"DESC":"ASC")}):b&&a.push(b+" ASC");return a}});