// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
require({cache:{"url:widgets/SmartEditor/setting/CopyAttributes.html":'\x3cdiv\x3e\r\n  \x3cdiv class\x3d"settingsDesc" data-dojo-attach-point\x3d"validationDesc"\x3e${nls.actionPage.description}\x3c/div\x3e\r\n  \x3cdiv data-dojo-attach-point\x3d"copyAttributeTable"\x3e\x3c/div\x3e\r\n  \x3cdiv style\x3d"color:red; display: none;" class\x3d"settingsNotes" data-dojo-attach-point\x3d"warningNote"\x3e${nls.actionPage.copyAttributesNote}\x3c/div\x3e\r\n\x3c/div\x3e'}});
define("dojo/_base/declare dojo/Evented dojo/query dojo/dom-style dijit/registry dojo/_base/lang dojo/_base/array dojo/on dojo/dom-construct dojo/text!./CopyAttributes.html dijit/_TemplatedMixin jimu/BaseWidgetSetting jimu/dijit/SimpleTable jimu/dijit/Popup esri/lang ./Intersection ./Coordinates ./Address".split(" "),function(n,p,l,h,q,e,f,g,k,r,t,u,v,m,w,x,y,z){return n([u,p,t],{baseClass:"jimu-widget-smartEditor-rule-table",templateString:r,_resourceInfo:null,_url:null,_fieldName:null,_fieldValues:null,
_configuredFieldValues:null,_layerId:null,_validGeocoderFields:[],_fieldsPopUp:null,_removeGroupInfo:null,_cbxForActionsWithGroupName:[],ValidFieldsForCoordinates:["esriFieldTypeSmallInteger","esriFieldTypeInteger","esriFieldTypeSingle","esriFieldTypeDouble","esriFieldTypeString"],ValidFieldsByType:{esriFieldTypeOID:["esriFieldTypeSmallInteger","esriFieldTypeInteger","esriFieldTypeSingle","esriFieldTypeDouble"],esriFieldTypeSmallInteger:["esriFieldTypeOID","esriFieldTypeSmallInteger","esriFieldTypeInteger",
"esriFieldTypeSingle","esriFieldTypeDouble"],esriFieldTypeInteger:["esriFieldTypeOID","esriFieldTypeSmallInteger","esriFieldTypeInteger","esriFieldTypeSingle","esriFieldTypeDouble"],esriFieldTypeDouble:["esriFieldTypeOID","esriFieldTypeSmallInteger","esriFieldTypeInteger","esriFieldTypeSingle","esriFieldTypeDouble"],esriFieldTypeSingle:["esriFieldTypeOID","esriFieldTypeSmallInteger","esriFieldTypeInteger","esriFieldTypeSingle","esriFieldTypeDouble"],esriFieldTypeGUID:["esriFieldTypeGUID","esriFieldTypeGlobalID"],
esriFieldTypeDate:["esriFieldTypeDate"],esriFieldTypeString:"esriFieldTypeSmallInteger esriFieldTypeInteger esriFieldTypeSingle esriFieldTypeDouble esriFieldTypeString esriFieldTypeGUID esriFieldTypeDate esriFieldTypeOID esriFieldTypeGlobalID".split(" ")},postCreate:function(){this.inherited(arguments);this._fieldsPopUp=null;this._configuredFieldValues=[];this._removeGroupInfo=null;this._initActionsTable();this._setActionsTable()},getSettings:function(){return this._fieldValues},_getConfigActionOrder:function(){var a=
[],b=[];this.isRelatedLayer?b=["Preset"]:(b=["Intersection"],this._validGeocoderFields=this._getValidGeocoderFields(),this._validGeocoderFields.length&&b.push("Address"),-1<this.ValidFieldsForCoordinates.indexOf(this._fieldType)&&b.push("Coordinates"),b.push("Preset"));return void 0!==this._fieldValues&&null!==this._fieldValues&&this._fieldValues.hasOwnProperty(this._fieldName)&&(f.forEach(this._fieldValues[this._fieldName],function(d){-1<b.indexOf(d.actionName)&&a.push(d.actionName)}),null!==a&&
0!==a.length)?a:b},_getValidGeocoderFields:function(){var a=[],b=[],a=this.ValidFieldsByType[this._fieldType];this._geocoderSettings&&this._geocoderSettings.hasOwnProperty("url")&&(b=f.filter(this._geocoderSettings.fields,function(b){return-1<a.indexOf(b.type)?!0:!1}));return b},_getConfigAction:function(a){var b=null;void 0!==this._fieldValues&&null!==this._fieldValues&&this._fieldValues.hasOwnProperty(this._fieldName)&&f.some(this._fieldValues[this._fieldName],function(d){return d.actionName===
a?(b=d,!0):!1});return b},_nlsActionToConfig:function(a){switch(a){case this.nls.actionPage.copyAction.intersection:return"Intersection";case this.nls.actionPage.copyAction.address:return"Address";case this.nls.actionPage.copyAction.coordinates:return"Coordinates";case this.nls.actionPage.copyAction.preset:return"Preset";default:return a}},popupActionsPage:function(){this._fieldsPopUp&&(this._fieldsPopUp.close(),this._fieldsPopUp=null);this._fieldsPopUp=new m({titleLabel:w.substitute({fieldname:this._fieldName},
this.nls.actionPage.title),width:920,maxHeight:600,autoHeight:!0,content:this,buttons:[{label:this.nls.ok,onClick:e.hitch(this,function(){var a=this._copyAttrTable.getRows();if(void 0===this._fieldValues||null===this._fieldValues)this._fieldValues={};this._fieldValues[this._fieldName]=[];f.forEach(a,function(b){var a;a=this._copyAttrTable.getRowData(b);b={};b.actionName=this._nlsActionToConfig(a.actionName);this._configuredFieldValues[b.actionName]?e.mixin(b,this._configuredFieldValues[b.actionName]):
e.mixin(b,{enabled:!1});e.mixin(b,{enabled:a.enabled});"Preset"===b.actionName&&this._configuredPresetInfos&&!this._configuredPresetInfos.hasOwnProperty(this._fieldName)&&(this._configuredPresetInfos[this._fieldName]=[""]);!b.enabled&&a.attributeActionGroupName&&(a={groupName:a.attributeActionGroupName,layerId:this._layerId,fieldName:this._fieldName,action:b.actionName},this.removeFromGroup(a),delete b.attributeActionGroupName);this._fieldValues[this._fieldName].push(b)},this);this._fieldsPopUp.close()})},
{label:this.nls.cancel,classNames:["jimu-btn jimu-btn-vacation"],onClick:e.hitch(this,function(){this._fieldsPopUp.close()})}],onClose:e.hitch(this,function(){})})},_initActionsTable:function(){this._copyAttrTable=new v({fields:[{name:"enabled",title:this.nls.actionPage.copyAction.enableText,type:"checkbox",width:"15%"},{name:"actionName",title:this.nls.actionPage.copyAction.actionText,type:"text"},{name:"attributeActionGroupName",title:this.nls.actionPage.actionsSettingsTable.groupName,type:"text"},
{name:"actions",title:this.nls.actionPage.copyAction.criteriaText,type:"actions",actions:["up","down","edit"],"class":"actions"}],selectable:!1,style:{height:"300px",maxHeight:"300px"}});this._copyAttrTable.placeAt(this.copyAttributeTable);this._copyAttrTable.startup();this.own(g(this._copyAttrTable,"actions-edit",e.hitch(this,this._onActionEdit)))},_onActionEdit:function(a){var b;this._removeGroupInfo=null;b=this._copyAttrTable.getRowData(a);if(b.attributeActionGroupName){var d,c;d=k.create("div");
k.create("div",{innerHTML:this.nls.actionPage.editOptionsPopup.editAttributeGroup,className:"settingsDesc"},d);k.create("div",{innerHTML:this.nls.actionPage.editOptionsPopup.editAttributeGroupHint,className:"editGroupHint"},d);c=new m({titleLabel:this.nls.actionPage.editOptionsPopup.popupTitle,width:500,maxHeight:445,autoHeight:!0,content:d,"class":this.baseClass,buttons:[{label:this.nls.actionPage.editOptionsPopup.editGroupButton,onClick:e.hitch(this,function(){this._editGroup(b);c.close()})},{label:this.nls.actionPage.editOptionsPopup.editIndependentlyButton,
disable:"Preset"===b.actionName?!0:!1,onClick:e.hitch(this,function(){b.attributeActionGroupName&&(this._removeGroupInfo={groupName:b.attributeActionGroupName,layerId:this._layerId,fieldName:this._fieldName,action:this._nlsActionToConfig(b.actionName)});this._onEditFieldInfoClick(a);c.close()})}]})}else this._onEditFieldInfoClick(a)},_onEditFieldInfoClick:function(a){switch(this._copyAttrTable.getRowData(a).actionName){case this.nls.actionPage.copyAction.intersection:this._createIntersectionPanel(a);
break;case this.nls.actionPage.copyAction.address:this._geocoderSettings&&this._geocoderSettings.hasOwnProperty("url")?this._createAddressPanel(a):this.emit("SetGeocoder");break;case this.nls.actionPage.copyAction.coordinates:this._createCoordinatesPanel(a)}},_removeFromGroup:function(a){this._removeGroupInfo&&(this.removeFromGroup(this._removeGroupInfo),this._copyAttrTable.editRow(a,{attributeActionGroupName:null}))},_createIntersectionPanel:function(a){this._intersectionDijit=x({nls:this.nls,_fieldValues:this._configuredFieldValues,
layerInfos:this.layerInfos,map:this.map,_fieldType:this._fieldType,isGroup:!1,ValidFieldsByType:this.ValidFieldsByType});this.own(g(this._intersectionDijit,"attributeActionUpdated",e.hitch(this,function(){this._removeFromGroup(a)})))},_createCoordinatesPanel:function(a){this._coordinatesDijit=y({nls:this.nls,isGroup:!1,_fieldType:this._fieldType,_fieldValues:this._configuredFieldValues});this.own(g(this._coordinatesDijit,"attributeActionUpdated",e.hitch(this,function(){this._removeFromGroup(a)})))},
_createAddressPanel:function(a){this._addressDijit=z({nls:this.nls,_fieldValues:this._configuredFieldValues,_geocoderSettings:this._geocoderSettings,_validGeocoderFields:this._validGeocoderFields,isGroup:!1});this.own(g(this._addressDijit,"attributeActionUpdated",e.hitch(this,function(){this._removeFromGroup(a)})))},_setActionsTable:function(){var a=this._getConfigActionOrder();this._cbxForActionsWithGroupName=[];f.forEach(a,function(b){var a=this._getConfigAction(b),c=b;switch(b){case "Intersection":this.nls.actionPage.hasOwnProperty("copyAction")&&
this.nls.actionPage.copyAction.hasOwnProperty("intersection")&&(c=this.nls.actionPage.copyAction.intersection);break;case "Address":this.nls.actionPage.hasOwnProperty("copyAction")&&this.nls.actionPage.copyAction.hasOwnProperty("address")&&(c=this.nls.actionPage.copyAction.address);break;case "Coordinates":this.nls.actionPage.hasOwnProperty("copyAction")&&this.nls.actionPage.copyAction.hasOwnProperty("coordinates")&&(c=this.nls.actionPage.copyAction.coordinates);break;case "Preset":this.nls.actionPage.hasOwnProperty("copyAction")&&
this.nls.actionPage.copyAction.hasOwnProperty("preset")&&(c=this.nls.actionPage.copyAction.preset);break;default:c=b}c={actionName:c};void 0!==a&&null!==a?this._configuredFieldValues[b]=a:(this._configuredFieldValues[b]={enabled:!1},"Intersection"===b&&(this._configuredFieldValues[b].fields=[]),"Coordinates"===b&&(this._configuredFieldValues[b].coordinatesSystem="MapSpatialReference",this._configuredFieldValues[b].field="x"));c.enabled=this._configuredFieldValues[b].enabled;this._configuredFieldValues[b].hasOwnProperty("attributeActionGroupName")&&
(c.attributeActionGroupName=this._configuredFieldValues[b].attributeActionGroupName);c.enabled&&"Preset"===b&&!this._configuredFieldValues[b].hasOwnProperty("attributeActionGroupName")&&(c.enabled=!1);a=this._copyAttrTable.addRow(c);c=l(".jimu-checkbox",a.tr)[0];c=q.byNode(c);"Preset"!==b||this._configuredFieldValues[b].hasOwnProperty("attributeActionGroupName")||(c.set("disabled",!0),(a=l(".jimu-icon-edit",a.tr))&&0<a.length&&h.set(a[0],"display","none"));this._configuredFieldValues[b].hasOwnProperty("attributeActionGroupName")&&
(this._cbxForActionsWithGroupName.push(c),this.own(g(c,"change",e.hitch(this,function(){var a=!0;f.some(this._cbxForActionsWithGroupName,function(b){b.getValue()||(a=!1,h.set(this.warningNote,"display","block"))},this);a&&h.set(this.warningNote,"display","none")}))))},this)},geocoderConfigured:function(){this._geocoderSettings&&this._geocoderSettings.hasOwnProperty("url")&&this._createAddressPanel()},_editGroup:function(a){var b,d;b=a.attributeActionGroupName;d=this._nlsActionToConfig(a.actionName);
this._copyAttrTable&&(a=this._attributeActionsTable[d].getRows(),f.some(a,function(a){if(this._attributeActionsTable[d].getRowData(a).name===b)return this._fieldsPopUp.close(),this.onGroupEditingStart(this.nls.layersPage.attributeActionsTabTitle),this._attributeActionsTable[d]._onActionsEdit(a),!0},this))},onGroupEditingStart:function(a){this.emit("onGroupEditingStart",a)},removeFromGroup:function(a){this.emit("removeFromGroup",a)}})});