// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
require({cache:{"url:widgets/SmartEditor/setting/RelativeDomains.html":'\x3cdiv\x3e\r\n  \x3cfieldset class\x3d"esriCTFieldset"\x3e\r\n    \x3clegend class\x3d"esriCTLegendTitle"\x3e${nls.relativeDomains.fieldSetTitle}\x3c/legend\x3e\r\n    \x3cdiv class\x3d"esriCTTableParentContainer" data-dojo-attach-point\x3d"tableParentContainer"\x3e\r\n    \x3c/div\x3e\r\n  \x3c/fieldset\x3e\r\n\x3c/div\x3e'}});
define("dojo/_base/declare dojo/Evented dojo/_base/lang dojo/on dojo/text!./RelativeDomains.html dijit/_WidgetsInTemplateMixin dojo/_base/array jimu/BaseWidgetSetting jimu/dijit/Popup jimu/dijit/SimpleTable jimu/dijit/Message jimu/utils dojo/query dijit/focus dijit/form/DateTextBox dijit/form/TimeTextBox dijit/form/NumberTextBox".split(" "),function(k,l,d,m,n,p,f,q,r,t,u,h,v,w){return k([q,l,p],{baseClass:"jimu-widget-smartEditor-setting-relativeDomains",templateString:n,domainObj:[],selectDomainValuePopup:null,
validNumericData:["esriFieldTypeSmallInteger","esriFieldTypeInteger","esriFieldTypeSingle","esriFieldTypeDouble"],postCreate:function(){this.domainObj=[];this.selectDomainValuePopup=null;this._createDomainTable();this._createSelectValuePopUp()},postMixInProperties:function(){this.nls=d.mixin(this.nls,window.jimuNls.common)},_createDomainTable:function(){this._domainTable=new t({fields:[{name:"selectDomain",title:"",type:"checkbox",width:"10%"},{name:"domainValue",title:this.nls.relativeDomains.valueText,
type:"text",width:"15%"},{name:"label",title:this.nls.label,type:"text",width:"55%"},{name:"defaultDomain",title:this.nls.relativeDomains.defaultText,type:"radio",width:"10%"},{name:"actions",title:this.nls.action,type:"actions",width:"10%%",actions:["up","down"],"class":"actions"}],selectable:!1});this._domainTable.startup();this._domainTable.placeAt(this.tableParentContainer);this._setValues()},_createSelectValuePopUp:function(){this.selectDomainValuePopup=new r({titleLabel:this.nls.chooseFromLayer.selectValueLabel,
width:800,height:500,autoHeight:!0,"class":this.baseClass,content:this,buttons:[{label:this.nls.ok,onClick:d.hitch(this,function(){var a=this._getValue();a&&(this.emit("updatePresetValue",a),this.selectDomainValuePopup.close())})},{label:this.nls.cancel,classNames:["jimu-btn-vacation"],onClick:d.hitch(this,function(){this.selectDomainValuePopup.close()})}]})},_getValue:function(){var a="",c=[],b=this._domainTable.getData();if(this._isValidConfiguration(b))return f.forEach(b,d.hitch(this,function(b){var e=
{};e.showInList=b.selectDomain;e.value="esriFieldTypeString"!==this.dataType?Number(b.domainValue):b.domainValue;e.label=b.label;e.isDefault=b.defaultDomain;e.isDefault&&(a=b.label);c.push(e)})),{domainData:c,defaultValue:a};new u({message:this.nls.relativeDomains.selectDefaultDomainMsg})},_setValues:function(){f.forEach(this.domainTableData,d.hitch(this,function(a){var c,b;c=this._domainTable.addRow({selectDomain:a.showInList,domainValue:""+a.value+"",label:a.label,defaultDomain:a.isDefault}).tr.cells[3].childNodes[0];
b=c.checked;this.own(m(c,"click",d.hitch(this,function(){b=b?c.checked=!1:c.checked=!0})))}))},_isValidConfiguration:function(a){var c=!1,b=!1,g=!1;f.some(a,d.hitch(this,function(a){a.defaultDomain&&(g=!0,a.selectDomain&&(b=!0));a.selectDomain&&(c=!0)}));return g?g&&b:c?c:!1},_support508ForSelectValuePopUp:function(){var a=v(".jimu-btn-vacation",this.selectDomainValuePopup.domNode)[0];h.initFirstFocusNode(this.selectDomainValuePopup.domNode,this.selectDomainValuePopup.closeBtnNode);w.focus(this.selectDomainValuePopup.closeBtnNode);
h.initLastFocusNode(this.selectDomainValuePopup.domNode,a)}})});