// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define(["dojo/_base/lang","dojo/_base/array","jimu/utils","./presetUtils"],function(m,n,q,p){var d={createPresetGroups:function(a,b){d.config=a;d._jimuLayerInfos=b;if(a.editor.presetInfos&&0<Object.keys(a.editor.presetInfos).length&&(a.attributeActionGroups?a.attributeActionGroups&&!a.attributeActionGroups.hasOwnProperty("Preset")&&(a.attributeActionGroups.Preset={}):a.attributeActionGroups={Intersection:{},Address:{},Coordinates:{},Preset:{}},!(a.attributeActionGroups&&a.attributeActionGroups.Preset&&
0<Object.keys(a.attributeActionGroups.Preset).length)))for(var e in a.editor.presetInfos)d._addPresetGroupForField(a.editor.configInfos||a.editor.layerInfos,e)},_getDomainListForPresetGroup:function(a,b,e){var g=[];n.forEach(b.domain.codedValues,m.hitch(this,function(c){var b={showInList:!0,value:c.code,label:c.name,isDefault:!1};a.showOnlyDomainFields=!0;var l=d.config.editor.presetInfos[e][0];"esriFieldTypeInteger"===a.dataType&&(l=Number(l));0<d.config.editor.presetInfos[e].length?c.code===l&&
(b.isDefault=!0):0===g.length&&(b.isDefault=!0);g.push(b)}));return g},_addPresetGroupForField:function(a,b){var e;n.some(a,m.hitch(this,function(a){if(e)return!0;if(a.fieldValues&&a.fieldValues[b])for(var c=a.fieldValues[b],f=0;f<c.length;f++)if("Preset"===c[f].actionName&&c[f].enabled){c[f].attributeActionGroupName=b;var g=d._jimuLayerInfos.getLayerOrTableInfoById(a.featureLayer.id);if(g&&g.layerObject&&g.layerObject.fields){f=p.getFieldInfoByFieldName(g.layerObject.fields,b);g=q.getDefaultPortalFieldInfo(f).label+
" ("+b+")";c={};c.name=g;0<["esriFieldTypeInteger","esriFieldTypeSmallInteger","esriFieldTypeInteger","esriFieldTypeSingle","esriFieldTypeDouble"].indexOf(f.type)?c.dataType="esriFieldTypeInteger":c.dataType=f.type;c.showOnlyDomainFields=!1;c.hideInPresetDisplay=!1;c.appliedOn=d._getPresetFieldsForAppliedOn(f,c);if(f.domain&&"range"!==f.domain.type)c.presetValue=d._getDomainListForPresetGroup(c,f,b);else if("esriFieldTypeDate"===f.type){var h,k;0<d.config.editor.presetInfos[b].length?(isNaN(d.config.editor.presetInfos[b][0])||
""===d.config.editor.presetInfos[b][0]||(k=new Date(d.config.editor.presetInfos[b][0])),d.config.editor.presetInfos[b][1]&&!isNaN(d.config.editor.presetInfos[b][1])&&(h=new Date(d.config.editor.presetInfos[b][1])),h=k&&h?new Date(k.getFullYear(),k.getMonth(),k.getDate(),h.getHours(),h.getMinutes(),h.getSeconds(),h.getMilliseconds()):k,c.presetValue=h?{dateType:"fixed",dateTime:h.getTime()}:{dateType:"fixed",dateTime:""}):c.presetValue={dateType:"fixed",dateTime:""}}else c.presetValue=0<d.config.editor.presetInfos[b].length?
d.config.editor.presetInfos[b][0]:null;d.config.attributeActionGroups.Preset[c.name]=c;e=!0;break}}!e&&a.relationshipInfos&&0<a.relationshipInfos.length&&(e=d._addPresetGroupForField(a.relationshipInfos,b))}));return e},_isPresetEnabledForLayer:function(a,b,e,g){if(a.fieldValues[b.name])for(var c=a.fieldValues[b.name],f=0;f<c.length;f++)if("Preset"===c[f].actionName&&c[f].enabled){var l=d._jimuLayerInfos.getLayerOrTableInfoById(a.featureLayer.id).layerObject.fields;p.getFieldInfoByFieldName(l,b.name).type===
b.type&&(c[f].attributeActionGroupName=g.name,e.hasOwnProperty(a.featureLayer.id)?e[a.featureLayer.id].push(b.name):e[a.featureLayer.id]=[b.name])}return e},_getPresetFieldsForAppliedOn:function(a,b){var e={};n.forEach(d.config.editor.configInfos||d.config.editor.layerInfos,m.hitch(this,function(g){g.fieldValues&&g.fieldValues[a.name]&&(e=d._isPresetEnabledForLayer(g,a,e,b));g.relationshipInfos&&0<g.relationshipInfos.length&&n.forEach(g.relationshipInfos,m.hitch(this,function(c){c.fieldValues&&c.fieldValues[a.name]&&
(e=d._isPresetEnabledForLayer(c,a,e,b))}))}));return e}};return d});