// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define("dojo/_base/lang jimu/utils dojo/date dojo/_base/array dojo/dom-construct dijit/form/DateTextBox dijit/form/NumberSpinner dijit/form/NumberTextBox dijit/form/FilteringSelect dijit/form/TextBox dijit/form/ValidationTextBox dijit/form/TimeTextBox dijit/Editor dijit/form/SimpleTextarea dojo/store/Memory".split(" "),function(h,l,d,f,e,m,n,k,p,g,q,r,t,u,v){return{integerFields:["esriFieldTypeSmallInteger","esriFieldTypeInteger","esriFieldTypeSingle","esriFieldTypeDouble"],getFieldInfoByFieldName:function(a,
c){var b={};f.some(a,function(a){if(a.name===c)return h.mixin(b,a),!0});return b},getDateFromRelativeInfo:function(a,c){var b=new Date;"fixed"===a.dateType?b=a.dateTime?new Date(a.dateTime):"":"future"===a.dateType?(b=d.add(b,"year",a.year),b=d.add(b,"month",a.month),b=d.add(b,"day",a.day),b=d.add(b,"hour",a.hour),b=d.add(b,"minute",a.minute),b=d.add(b,"second",a.second)):"past"===a.dateType&&(a.year&&(b=d.add(b,"year",-1*a.year)),a.month&&(b=d.add(b,"month",-1*a.month)),a.day&&(b=d.add(b,"day",-1*
a.day)),a.hour&&(b=d.add(b,"hour",-1*a.hour)),a.minute&&(b=d.add(b,"minute",-1*a.minute)),a.second&&(b=d.add(b,"second",-1*a.second)));return c&&""!==b?l.localizeDate(b):b},getDateFieldValue:function(a,c){var b;if("esriFieldTypeDate"===a.type){if(c instanceof Array){var d,e;0<c.length&&c[0]&&(d=c[0].getValue());1<c.length&&c[1]&&(e=c[1].getValue());b=d&&e?new Date(d.getFullYear(),d.getMonth(),d.getDate(),e.getHours(),e.getMinutes(),e.getSeconds(),e.getMilliseconds()):d||e||null}else b=c.getValue(),
a.domain&&(b=Number(b));b=b&&b.getTime?b.getTime():b&&b.toGregorian?b.toGregorian().getTime():b}return b},isGuid:function(a){"{"===a[0]&&(a=a.substring(1,a.length-1));return/^(\{){0,1}[0-9a-fA-F]{8}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{12}(\}){0,1}$/gi.test(a)},validateGUID:function(a,c){return this.isGuid(a)},isValidPresetValue:function(a){var c=!0;f.some(a,function(a){if(a.isValid&&!a.isValid())return c=!1,!0});return c},createPresetFieldContentNode:function(a){var c=[],
b;if(a.domain){if("codedValue"===a.domain.type){var d=[];f.forEach(a.domain.codedValues,function(a){d.push({name:a.name,id:a.code})});b=new p({"class":"ee-inputField",name:a.fieldName,store:new v({data:d}),searchAttr:"name",required:!1},e.create("div"))}else{b=null;switch(a.type){case "esriFieldTypeSmallInteger":case "esriFieldTypeInteger":b={min:a.domain.minValue,max:a.domain.maxValue,places:0};break;case "esriFieldTypeSingle":case "esriFieldTypeDouble":b={min:a.domain.minValue,max:a.domain.maxValue}}b=
new n({"class":"ee-inputField",name:a.fieldName,smallDelta:1,constraints:b},e.create("div"))}c.push(b)}else switch(a.type){case "esriFieldTypeGUID":b=new q({"class":"ee-inputField",name:a.fieldName},e.create("div"));b.validator=h.hitch(this,this.validateGUID);c.push(b);break;case "esriFieldTypeDate":b=new m({"class":"ee-inputField",name:a.fieldName},e.create("div"));c.push(b);a.format&&a.format.time&&!0===a.format.time&&(a=new r({"class":"ee-inputField",style:"margin-top:2px;"},e.create("div")),c.push(a));
break;case "esriFieldTypeString":b=null;a.length&&Number(a.length)&&0<Number(a.length)&&(b=a.length);a.hasOwnProperty("stringFieldOption")?"richtext"===a.stringFieldOption?(b={"class":"ee-inputField ee-inputFieldRichText",trim:!0,maxLength:b},b["class"]+=" atiRichTextField",b.height="100%",b.width="100%",b.name=a.fieldName,b.plugins="bold italic underline foreColor hiliteColor | justifyLeft justifyCenter justifyRight justifyFull | insertOrderedList insertUnorderedList indent outdent | createLink".split(" "),
b=new t(b,e.create("div")),b.startup()):b="textarea"===a.stringFieldOption?new u({"class":"ee-inputField ee-inputFieldTextArea",name:a.fieldName,maxlength:b},e.create("div")):new g({"class":"ee-inputField",name:a.fieldName,maxlength:b},e.create("div")):b=new g({"class":"ee-inputField",name:a.fieldName,maxlength:b},e.create("div"));c.push(b);break;case "esriFieldTypeSmallInteger":case "esriFieldTypeInteger":b=new k({"class":"ee-inputField",name:a.fieldName,constraints:{places:0}},e.create("div"));
c.push(b);break;case "esriFieldTypeSingle":case "esriFieldTypeDouble":b=new k({"class":"ee-inputField",name:a.fieldName},e.create("div"));c.push(b);break;default:b=new g({"class":"ee-unsupportField",name:a.fieldName,value:"N/A",readOnly:!0},e.create("div")),c.push(b)}return c},changeFieldToMostRestrictive:function(a,c){if(!a.hasOwnProperty("type")&&c.hasOwnProperty("type"))return c;c.length&&Number(c.length)&&0<Number(c.length)&&(a.length&&Number(a.length)?c.length<a.length&&(a.length=c.length):a.length=
c.length);if(a.type===c.type)switch(c.type){case "esriFieldTypeString":a.hasOwnProperty("stringFieldOption")&&c.hasOwnProperty("stringFieldOption")&&("richtext"===a.stringFieldOption&&"richtext"!==c.stringFieldOption?a.stringFieldOption=c.stringFieldOption:"textarea"===a.stringFieldOption&&"textbox"===c.stringFieldOption&&(a.stringFieldOption=c.stringFieldOption))}return a}}});