// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define("dojo/_base/declare dojo/Evented dojo/_base/lang dojo/_base/array dojo/dom-construct dojo/dom-class dojo/on dojo/keys dojo/string dojo/dom-attr dojo/mouse ./presetUtils ./setting/RelativeDates dijit/_TemplatedMixin jimu/BaseWidgetSetting dijit/form/FilteringSelect dojo/store/Memory dijit/form/ValidationTextBox dijit/form/NumberTextBox esri/urlUtils jimu/dijit/Message jimu/utils".split(" "),function(v,w,f,q,e,x,g,k,p,h,y,l,t,z,A,B,C,r,D,E,u,F){return v([A,w,z],{baseClass:"jimu-widget-smartEditor-setting-preset",
tooltipContents:{},hasAtLeastOneGroupInDisplay:!1,enableUsePresetValueCheckBox:!1,postCreate:function(){this.inherited(arguments);this.enableUsePresetValueCheckBox=this.hasAtLeastOneGroupInDisplay=!1;this.tooltipContents={};this.presetContainer=e.create("div",{"class":"esriCTPresetContent"},this.parentNode);this._createPresetContents()},_fetchUrlParameters:function(){var a,b;a=E.urlToObject(document.location.href);a.query&&(b=a.query);return b},_createPresetContents:function(){var a,b;b=this._fetchUrlParameters();
for(a in this._configuredPresetInfos){var c;c=this._isGroupNameFound(b,a);c=b&&c.isConfiguredGroupName?this._createPresetContentDOM(this._configuredPresetInfos[a],b[c.urlParamKey]):this._createPresetContentDOM(this._configuredPresetInfos[a]);this._configuredPresetInfos[a].hideInPresetDisplay?x.add(c,"esriCTHidden"):this.hasAtLeastOneGroupInDisplay=!0;this._createTooltipContent(this._configuredPresetInfos[a])}},_isGroupNameFound:function(a,b){var c=!1,d;a&&q.forEach(Object.keys(a),f.hitch(this,function(a){if(a.toLowerCase()===
b.toLowerCase())return c=!0,d=a,!0}));return{isConfiguredGroupName:c,urlParamKey:d}},_createPresetContentDOM:function(a,b){var c=e.create("tr"),d=e.create("td"),m=e.create("div",{"class":"esriCTGroupInfoIcon","aria-label":p.substitute(this.nls.groupInfoLabel,{groupName:a.name}),tabindex:"0",role:"button"},d),G=e.create("span",{innerHTML:a.name,"class":"ee-atiLabel"},d);h.set(G,"groupName",a.name);h.set(m,"groupName",a.name);this.own(g(m,"click",f.hitch(this,function(a){a=h.get(a.currentTarget,"groupName");
u({message:this.tooltipContents[a].innerHTML})})));this.own(g(m,"keydown",f.hitch(this,function(a){if(a.keyCode===k.ENTER||a.keyCode===k.SPACE)a=h.get(a.currentTarget,"groupName"),u({message:this.tooltipContents[a].innerHTML})})));e.place(d,c);d=e.create("td",{"class":"preset-value-editable"},c);if(a.showOnlyDomainFields)a=this._createDomainContentNode(a,d),void 0!==b&&a.set("value",b);else switch(a.dataType){case "esriFieldTypeInteger":void 0===b||isNaN(b)||(a.presetValue=b);this._createNumberTypeDOM(a,
d);break;case "esriFieldTypeDate":void 0!==b&&(a.presetValue={dateType:"fixed",dateTime:isNaN(b)?null:Number(b)});this._createDateTypeDOM(a,d);break;case "esriFieldTypeString":void 0!==b&&(a.presetValue=b);this._createStringTypeDOM(a,d);break;case "esriFieldTypeGUID":void 0!==b&&(a.presetValue=b),this._createGUIDTypeDOM(a,d)}this.parentNode.appendChild(c);return c},_createTooltipContent:function(a){var b,c,d,m,g=!1,k=e.create("div");c=e.create("div",{"class":"presetMessageContentDiv",style:{"max-height":"200px",
overflow:"auto"},tabindex:"0"},k);d=p.substitute(this.nls.presetGroupFieldsLabel,{groupName:"\x3cb\x3e"+a.name+"\x3c/b\x3e"});m=p.substitute(this.nls.presetGroupNoFieldsLabel,{groupName:"\x3cb\x3e"+a.name+"\x3c/b\x3e"});d=e.create("div",{innerHTML:d},c);c=e.create("ul",{style:"margin: 0px; padding: 0 20px;"},c);for(b in a.appliedOn)if(0<a.appliedOn[b].length){var g=!0,n=this._jimuLayerInfos.getLayerOrTableInfoById(b);if(n&&n.title&&n.layerObject&&n.layerObject.fields){e.create("li",{innerHTML:n.title+
": "},c);var l=e.create("ul",{style:"margin: 0px;"},c);q.forEach(n.layerObject.fields,f.hitch(this,function(c){c=F.getDefaultPortalFieldInfo(c);0<=a.appliedOn[b].indexOf(c.fieldName)&&e.create("li",{innerHTML:c.label||c.fieldName},l)}))}}g||h.set(d,"innerHTML",m);this.tooltipContents[a.name]=k},_enableUsePresetValueCB:function(a){null!==a&&""!==a&&void 0!==a&&(this.enableUsePresetValueCheckBox=!0)},_createNumberTypeDOM:function(a,b){b=new D({"class":"ee-inputField",name:a.name,value:a.presetValue,
"aria-label":a.name},e.create("div",{},b));this.own(g(b,"change",f.hitch(this,function(c){a.presetValue=c;this.emit("presetValueChanged")})));this._enableUsePresetValueCB(a.presetValue)},_createDateTypeDOM:function(a,b){var c,d;c=new r({"class":"ee-inputField",name:a.name,disabled:!0,"aria-label":a.name,style:"width: calc(100% - 30px)",value:this.nls.relativeDates[a.presetValue.dateType]},e.create("div",{},b));"fixed"===a.presetValue.dateType&&(a.presetValue.dateTime?c.set("value",l.getDateFromRelativeInfo(a.presetValue,
!0)):c.set("value",""));h.set(c.focusNode,"disabled",!1);h.set(c.focusNode,"readonly",!0);h.set(c.focusNode,"tabindex",0);c.esriCTisDateGroup=!0;c.esriCTPresetGroup=a;d=p.substitute(this.nls.editGroupInfoIcon,{groupName:a.name});b=e.create("div",{"class":"jimu-icon jimu-icon-edit",tabindex:"0",role:"button","aria-label":d},e.create("div",{"class":"editRelativeDateIcon"},b));this.own(g(b,"click",f.hitch(this,function(){var b=new t({nls:this.nls,relativeDates:a.presetValue});this.own(g(b,"updatePresetValue",
f.hitch(this,function(b){a.presetValue=b;"fixed"===a.presetValue.dateType?a.presetValue.dateTime?c.set("value",l.getDateFromRelativeInfo(a.presetValue,!0)):c.set("value",""):c.set("value",this.nls.relativeDates[b.dateType]);this.emit("presetValueChanged")})))})));this.own(g(b,"keydown",f.hitch(this,function(b){if(b.keyCode===k.ENTER||b.keyCode===k.SPACE)b=new t({nls:this.nls,relativeDates:a.presetValue}),this.own(g(b,"updatePresetValue",f.hitch(this,function(b){a.presetValue=b;"fixed"===a.presetValue.dateType?
a.presetValue.dateTime?c.set("value",l.getDateFromRelativeInfo(a.presetValue,!0)):c.set("value",""):c.set("value",this.nls.relativeDates[b.dateType]);this.emit("presetValueChanged")})))})));this.own(g(c.domNode,y.enter,f.hitch(this,function(){var b=l.getDateFromRelativeInfo(a.presetValue,!0);""===b&&(b=this.nls.relativeDates.noDateDefinedTooltip);c.set("title",b)})));this._enableUsePresetValueCB(a.presetValue)},_createStringTypeDOM:function(a,b){b=new r({"class":"ee-inputField",name:a.name,"aria-label":a.name,
value:a.presetValue},e.create("div",{},b));this.own(g(b,"change",f.hitch(this,function(b){a.presetValue=b;this.emit("presetValueChanged")})));this._enableUsePresetValueCB(a.presetValue)},_createGUIDTypeDOM:function(a,b){b=new r({"class":"ee-inputField","aria-label":a.name,name:a.name,value:a.presetValue},e.create("div",{},b));this.own(g(b,"change",f.hitch(this,function(b){a.presetValue=b;this.emit("presetValueChanged")})));this._enableUsePresetValueCB(a.presetValue)},_createDomainContentNode:function(a,
b){var c,d;c=this._populateDomains(a);d=new B({"class":"ee-inputField",name:a.name,"aria-label":a.name,style:{width:"99%"},required:!1,store:new C({data:c.options})},e.create("div",{},b));d.esriCTDomainList=!0;this.own(g(d,"change",f.hitch(this,function(){a.selectedDomainValue=d.get("value");this.emit("presetValueChanged")})));d.set("value",c.defaultValue);this._enableUsePresetValueCB(a.presetValue);return d},_populateDomains:function(a){var b=[],c;q.forEach(a.presetValue,f.hitch(this,function(d){d.showInList&&
(b.push({name:d.label,id:d.value}),d.isDefault&&(c=d.value,a.selectedDomainValue=d.value))}));return{options:b,defaultValue:c}}})});